DROP LOGIN [SYSADM] 
GO
CREATE LOGIN [SYSADM] WITH PASSWORD=N'SYSADM', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [SYSADM]
GO
ALTER USER [SYSADM] WITH Login = [SYSADM]
GO