CREATE Login ALLE with PASSWORD = 'sqlporter' 
GO

CREATE USER ALLE FOR LOGIN ALLE
GO

CREATE Login BEVERBUR with PASSWORD = 'sqlporter' 
GO

CREATE USER BEVERBUR FOR LOGIN BEVERBUR
GO

CREATE Login FRIEDRIC with PASSWORD = 'sqlporter' 
GO

CREATE USER FRIEDRIC FOR LOGIN FRIEDRIC
GO

CREATE Login HENNECKE with PASSWORD = 'sqlporter' 
GO

CREATE USER HENNECKE FOR LOGIN HENNECKE
GO

CREATE Login INTENSIO with PASSWORD = 'sqlporter' 
GO

CREATE USER INTENSIO FOR LOGIN INTENSIO
GO

CREATE Login KEUER with PASSWORD = 'sqlporter' 
GO

CREATE USER KEUER FOR LOGIN KEUER
GO

CREATE Login KOLLAY with PASSWORD = 'sqlporter' 
GO

CREATE USER KOLLAY FOR LOGIN KOLLAY
GO

CREATE Login MARTIN with PASSWORD = 'sqlporter' 
GO

CREATE USER MARTIN FOR LOGIN MARTIN
GO

CREATE Login ODBC with PASSWORD = 'sqlporter' 
GO

CREATE USER ODBC FOR LOGIN ODBC
GO

CREATE Login SASSE with PASSWORD = 'sqlporter' 
GO

CREATE USER SASSE FOR LOGIN SASSE
GO

CREATE Login SC with PASSWORD = 'sqlporter' 
GO

CREATE USER SC FOR LOGIN SC
GO

CREATE Login SD with PASSWORD = 'sqlporter' 
GO

CREATE USER SD FOR LOGIN SD
GO

CREATE Login SEIL with PASSWORD = 'sqlporter' 
GO

CREATE USER SEIL FOR LOGIN SEIL
GO

CREATE Login SQLMON with PASSWORD = 'sqlporter' 
GO

CREATE USER SQLMON FOR LOGIN SQLMON
GO

CREATE Login STUKE with PASSWORD = 'sqlporter' 
GO

CREATE USER STUKE FOR LOGIN STUKE
GO

CREATE Login SYMOLKA with PASSWORD = 'sqlporter' 
GO

CREATE USER SYMOLKA FOR LOGIN SYMOLKA
GO

CREATE Login TIERARZT with PASSWORD = 'sqlporter' 
GO

CREATE USER TIERARZT FOR LOGIN TIERARZT
GO

CREATE Login ZINK with PASSWORD = 'sqlporter' 
GO

CREATE USER ZINK FOR LOGIN ZINK
GO

CREATE Login ZK with PASSWORD = 'sqlporter' 
GO

CREATE USER ZK FOR LOGIN ZK
GO

