CREATE INDEX XAAARZT ON [dbo].[AERZTEANSPRECH] ([AAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XAPARZT ON [dbo].[AERZTEPERSONEN] ([APARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XAKARZTNR ON [dbo].[AKTIONEN] ([AKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XAKDEAKTIV ON [dbo].[AKTIONEN] ([AKDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XAKHALTERARZT ON [dbo].[AKTIONEN] ([AKHALTERNR],[AKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XAKPROZNR ON [dbo].[AKTIONEN] ([AKPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XAKTYP ON [dbo].[AKTIONEN] ([AKTYP] ) ON [PRIMARY]
GO

CREATE INDEX XABARZT ON [dbo].[ANWEISUNGSBELEGE] ([ABARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XABDRUDAT ON [dbo].[ANWEISUNGSBELEGE] ([ABDRUDAT] ) ON [PRIMARY]
GO

CREATE INDEX XBEZARZTNR ON [dbo].[BANKEINZUG] ([BEZARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XBIARZT ON [dbo].[BEHANDLUNGSIDS] ([BIARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XBIERFDAT ON [dbo].[BEHANDLUNGSIDS] ([BIERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XBIRECHNR ON [dbo].[BEHANDLUNGSIDS] ([BIRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XBIUEBDAT ON [dbo].[BEHANDLUNGSIDS] ([BIUEBDAT] ) ON [PRIMARY]
GO

CREATE INDEX XBEERLDAT ON [dbo].[BEIHILFEN] ([BEERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XBEREGHALTER ON [dbo].[BEIHILFEN] ([BEREGHALTER] ) ON [PRIMARY]
GO

CREATE INDEX XBEZDARZT ON [dbo].[BEZDATEN] ([BEZDARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XBEZDDEAKTIV ON [dbo].[BEZDATEN] ([BEZDDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XBEZDERLDAT ON [dbo].[BEZDATEN] ([BEZDERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XBEZDHALTER ON [dbo].[BEZDATEN] ([BEZDHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XBEZSARZT ON [dbo].[BEZSTAMM] ([BEZSARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XBEZSDEAKTIV ON [dbo].[BEZSTAMM] ([BEZSDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XBEZSHALTER ON [dbo].[BEZSTAMM] ([BEZSHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XBLZBLZ ON [dbo].[BLZ] ([BLZBLZ] ) ON [PRIMARY]
GO

CREATE INDEX BUBERLDAT ON [dbo].[BUCHBEL] ([BUBERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XDSCODE ON [dbo].[DATEVSTAMM] ([DSCODE] ) ON [PRIMARY]
GO

CREATE INDEX XDDARZT ON [dbo].[DOPPDRUCK] ([DDARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XDKARZTNR ON [dbo].[DRUKON] ([DKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XDKERLDAT ON [dbo].[DRUKON] ([DKERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XDKINKL ON [dbo].[DRUKON] ([DKINKL] ) ON [PRIMARY]
GO

CREATE INDEX XDKRECHNR ON [dbo].[DRUKON] ([DKRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XDLERLDAT ON [dbo].[DRULISTE] ([DLERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XELARZTNR ON [dbo].[ERINNERUNGSLISTE] ([ELARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XELDEAKTIV ON [dbo].[ERINNERUNGSLISTE] ([ELDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XELERLEDITG ON [dbo].[ERINNERUNGSLISTE] ([ELERLEDIGT] ) ON [PRIMARY]
GO

CREATE INDEX XELHALTERNR ON [dbo].[ERINNERUNGSLISTE] ([ELHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XELZEICHEN ON [dbo].[ERINNERUNGSLISTE] ([ELZEICHEN] ) ON [PRIMARY]
GO

CREATE INDEX XEWAARZT ON [dbo].[EWA] ([EWAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XEWADEAKTIV ON [dbo].[EWA] ([EWADEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XEWAHALTER ON [dbo].[EWA] ([EWAHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XEEDATUM ON [dbo].[EWAERINNERUNG] ([EEDATUM] ) ON [PRIMARY]
GO

CREATE INDEX XEEDEAKTIV ON [dbo].[EWAERINNERUNG] ([EEDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XEEERLDAT ON [dbo].[EWAERINNERUNG] ([EEERLDATUM] ) ON [PRIMARY]
GO

CREATE INDEX XEEZEI ON [dbo].[EWAERINNERUNG] ([EEZEI] ) ON [PRIMARY]
GO

CREATE INDEX XFIBELDAT ON [dbo].[FIBU] ([FIBELDAT] ) ON [PRIMARY]
GO

CREATE INDEX XFIFERTIG ON [dbo].[FIBU] ([FIFERTIG] ) ON [PRIMARY]
GO

CREATE INDEX XFIHABEN ON [dbo].[FIBU] ([FIHABEN] ) ON [PRIMARY]
GO

CREATE INDEX XFISOLL ON [dbo].[FIBU] ([FISOLL] ) ON [PRIMARY]
GO

CREATE INDEX XFIUEBDAT ON [dbo].[FIBU] ([FIUEBDAT] ) ON [PRIMARY]
GO

CREATE INDEX XFAPROZNR ON [dbo].[FORDAUFS] ([FAPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XGEBEZ ON [dbo].[GERICHTE] ([GEBEZ] ) ON [PRIMARY]
GO

CREATE INDEX XHBARZTNR ON [dbo].[HABU] ([HBARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XHBDEAKTIV ON [dbo].[HABU] ([HBDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XHBERFDAT ON [dbo].[HABU] ([HBERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XHBHALTER ON [dbo].[HABU] ([HBARZTNR],[HBHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XHBHALTERNR ON [dbo].[HABU] ([HBHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XHBRECHNR ON [dbo].[HABU] ([HBRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XHBRZNR ON [dbo].[HABU] ([HBRZNR] ) ON [PRIMARY]
GO

CREATE INDEX XHARZTNR ON [dbo].[HALTER] ([HARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XHDEAKTIV ON [dbo].[HALTER] ([HDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XHERFDAT ON [dbo].[HALTER] ([HERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XHMAHNINT ON [dbo].[HALTER] ([HMAHNINT] ) ON [PRIMARY]
GO

CREATE INDEX XHNN ON [dbo].[HALTER] ([HNN] ) ON [PRIMARY]
GO

CREATE INDEX XHVIRTKONTO ON [dbo].[HALTER] ([HVIRTKONTO] ) ON [PRIMARY]
GO

CREATE INDEX XSOUNDEXHNN ON [dbo].[HALTER] ([HNN] ) ON [PRIMARY]
GO

CREATE INDEX XINIENTRY ON [dbo].[INITIALISIERUNG] ([INIENTRY] ) ON [PRIMARY]
GO

CREATE INDEX XINISECTION ON [dbo].[INITIALISIERUNG] ([INISECTION] ) ON [PRIMARY]
GO

CREATE INDEX IACODE ON [dbo].[INVAD] ([IACODE] ) ON [PRIMARY]
GO

CREATE INDEX IKARZTNR ON [dbo].[INVKO] ([IKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX IPARZTNR ON [dbo].[INVPO] ([IPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XKOCODE ON [dbo].[KONTIERUNGEN] ([KOCODE] ) ON [PRIMARY]
GO

CREATE INDEX XLCCODE ON [dbo].[LAENDERCODES] ([LCCODE] ) ON [PRIMARY]
GO

CREATE INDEX XLEARZTNR ON [dbo].[LEISERF] ([LEARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEHALTERNR ON [dbo].[LEISERF] ([LEHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEPOSNR ON [dbo].[LEISERF] ([LEPOSNR] ) ON [PRIMARY]
GO

CREATE INDEX XLERECHNR ON [dbo].[LEISERF] ([LERECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEPARZTNR ON [dbo].[LEISERFPOS] ([LEPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEPHALTERNR ON [dbo].[LEISERFPOS] ([LEPHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEPLA ON [dbo].[LEISERFPOS] ([LEPLA] ) ON [PRIMARY]
GO

CREATE INDEX XLEPPOSNR ON [dbo].[LEISERFPOS] ([LEPPOSNR] ) ON [PRIMARY]
GO

CREATE INDEX XLEPRECHNR ON [dbo].[LEISERFPOS] ([LEPRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XLTARZT ON [dbo].[LOESCHTEMP] ([LTARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XLTHALTER ON [dbo].[LOESCHTEMP] ([LTHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XLOGDATE ON [dbo].[LOG] ([LOGDATE] ) ON [PRIMARY]
GO

CREATE INDEX XLOGTYP ON [dbo].[LOG] ([LOGTYP] ) ON [PRIMARY]
GO

CREATE INDEX XLBBEZ ON [dbo].[LOGBUG] ([LBBEZ] ) ON [PRIMARY]
GO

CREATE INDEX XMDDATUM ON [dbo].[MAHNDATEN] ([MDDATUM] ) ON [PRIMARY]
GO

CREATE INDEX XMDDEAKTIV ON [dbo].[MAHNDATEN] ([MDDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XMDHALTERARZT ON [dbo].[MAHNDATEN] ([MDHALTERNR],[MDARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XMAARZTHALTER ON [dbo].[MAHNUNGEN] ([MAARZTNR],[MAHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XMAARZTNR ON [dbo].[MAHNUNGEN] ([MAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XMAARZTRECH ON [dbo].[MAHNUNGEN] ([MAARZTNR],[MARECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XMADATUM ON [dbo].[MAHNUNGEN] ([MADATUM] ) ON [PRIMARY]
GO

CREATE INDEX XMADEAKTIV ON [dbo].[MAHNUNGEN] ([MADEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XMANR ON [dbo].[MAHNUNGEN] ([MANR] ) ON [PRIMARY]
GO

CREATE INDEX XMBKDEAKTIV ON [dbo].[MBKALENDER] ([MBKDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XMBKPROZNR ON [dbo].[MBKALENDER] ([MBKPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XMCGEM ON [dbo].[MCGEM] ([ID] ) ON [PRIMARY]
GO

CREATE INDEX XMCKREIS ON [dbo].[MCKREIS] ([ID] ) ON [PRIMARY]
GO

CREATE INDEX XMCORTORT ON [dbo].[MCORT] ([IDORT] ) ON [PRIMARY]
GO

CREATE INDEX XMCORTTORT ON [dbo].[MCORTT] ([ORT] ) ON [PRIMARY]
GO

CREATE INDEX XMCORTTPLZ ON [dbo].[MCORTT] ([PLZ] ) ON [PRIMARY]
GO

CREATE INDEX XMCPLZ ON [dbo].[MCPLZ] ([PLZ] ) ON [PRIMARY]
GO

CREATE INDEX XMCSTRPLZ ON [dbo].[MCSTR] ([PLZ] ) ON [PRIMARY]
GO

CREATE INDEX XNRCODE ON [dbo].[NUMMERN] ([NRCODE] ) ON [PRIMARY]
GO

CREATE INDEX XPIHAUPTNR ON [dbo].[PACKINFO] ([PIHAUPTNR] ) ON [PRIMARY]
GO

CREATE INDEX XPEARZTNR ON [dbo].[PERSONEN] ([PEARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XPREPROZNR ON [dbo].[PREDA] ([PREPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRIDID ON [dbo].[PRINTIDS] ([PRIDID] ) ON [PRIMARY]
GO

CREATE INDEX XPRARZTNR ON [dbo].[PROZREG] ([PRARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRBEZAHLT ON [dbo].[PROZREG] ([PRBEZAHLT] ) ON [PRIMARY]
GO

CREATE INDEX XPRDEAKTIV ON [dbo].[PROZREG] ([PRDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XPRDRUCKDATUM ON [dbo].[PROZREG] ([PRDRUCKDATUM] ) ON [PRIMARY]
GO

CREATE INDEX XPRHALTERNR ON [dbo].[PROZREG] ([PRHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRNR ON [dbo].[PROZREG] ([PRNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRD ON [dbo].[PROZREGDET] ([PRDARZTNR],[PRDHALTERNR],[PRDRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRDARZTNR ON [dbo].[PROZREGDET] ([PRDARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRDNR ON [dbo].[PROZREGDET] ([PRDNR] ) ON [PRIMARY]
GO

CREATE INDEX XPRDRECHNR ON [dbo].[PROZREGDET] ([PRDRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XRZARZT ON [dbo].[RAZA] ([RZARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRZDEAKTIV ON [dbo].[RAZA] ([RZDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XRZNR ON [dbo].[RAZA] ([RZNR] ) ON [PRIMARY]
GO

CREATE INDEX CRZPNR ON [dbo].[RAZAPOS] ([RZPNR] ) ON [PRIMARY]
GO

CREATE INDEX XRZPARZT ON [dbo].[RAZAPOS] ([RZPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRZPHALTERNR ON [dbo].[RAZAPOS] ([RZPHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XRAARZTNR ON [dbo].[RECHAB] ([RAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRBARZT ON [dbo].[RECHBUCH] ([RBARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRBHALTERNR ON [dbo].[RECHBUCH] ([RBHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XRBRECHNR ON [dbo].[RECHBUCH] ([RBRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XRECHARZT ON [dbo].[RECHKO] ([RKRECHNR],[RKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRKARZTNR ON [dbo].[RECHKO] ([RKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRKBEGUID ON [dbo].[RECHKO] ([RKBEGUID] ) ON [PRIMARY]
GO

CREATE INDEX XRKDATEVDATE ON [dbo].[RECHKO] ([RKDATEVDATE] ) ON [PRIMARY]
GO

CREATE INDEX XRKDEAKTIV ON [dbo].[RECHKO] ([RKDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XRKHALTERARZT ON [dbo].[RECHKO] ([RKHALTERNR],[RKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRKKZZAHL ON [dbo].[RECHKO] ([RKKZZAHL] ) ON [PRIMARY]
GO

CREATE INDEX XRKMAHNSPERR ON [dbo].[RECHKO] ([RKMAHNSPERR] ) ON [PRIMARY]
GO

CREATE INDEX XRKMAHNSTUFE ON [dbo].[RECHKO] ([RKMAHNSTUFE] ) ON [PRIMARY]
GO

CREATE INDEX XRKRECHDAT ON [dbo].[RECHKO] ([RKRECHDAT] ) ON [PRIMARY]
GO

CREATE INDEX XRKVECODE ON [dbo].[RECHKO] ([RKVECODE] ) ON [PRIMARY]
GO

CREATE INDEX XRKVORSCHUSSRUECKDAT ON [dbo].[RECHKO] ([RKVORSCHUSSRUECKDAT] ) ON [PRIMARY]
GO

CREATE INDEX XRECHARZT2 ON [dbo].[RECHKO2] ([RKRECHNR],[RKARZTNR] ) ON [PRIMARY]
GO

CREATE UNIQUE INDEX XRECHKO2 ON [dbo].[RECHKO2] ([RKARZTNR],[RKHALTERNR],[RKRECHNR] ) ON [PRIMARY]
GO

CREATE INDEX XRPHDA ON [dbo].[RECHPO] ([RPHALTERNR],[RPDATUM],[RPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRPRECHARZT ON [dbo].[RECHPO] ([RPRECHNR],[RPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRPRECHPOROWID ON [dbo].[RECHPO] ([ROWID] ) ON [PRIMARY]
GO

CREATE INDEX XRIARZT ON [dbo].[RISER] ([RIARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XRIHALTER ON [dbo].[RISER] ([RIHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XRRDATUM ON [dbo].[RUECKRUF] ([RRDATUM] ) ON [PRIMARY]
GO

CREATE INDEX XRRERLDAT ON [dbo].[RUECKRUF] ([RRERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XSLSTART ON [dbo].[SUPPORTLOG] ([SLSTART] ) ON [PRIMARY]
GO

CREATE INDEX TKARZTNR ON [dbo].[TAKONTO] ([TKARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XTEARZTHALTER ON [dbo].[TELEFON] ([TEARZTNR],[TEHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX TKAARZTNR ON [dbo].[TKALT] ([TKAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX TKADRUCKDATUM ON [dbo].[TKALT] ([TKADRUCKDATUM] ) ON [PRIMARY]
GO

CREATE INDEX TKAMWST ON [dbo].[TKALT] ([TKAPROZMWST] ) ON [PRIMARY]
GO

CREATE INDEX XTKAARZTNR ON [dbo].[TKALT] ([TKAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XTKABELDAT ON [dbo].[TKALT] ([TKABELDAT] ) ON [PRIMARY]
GO

CREATE INDEX XTKADEAKTIV ON [dbo].[TKALT] ([TKADEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XTKAFALL ON [dbo].[TKALT] ([TKAFALL] ) ON [PRIMARY]
GO

CREATE INDEX XTKAHABEN ON [dbo].[TKALT] ([TKHABEN] ) ON [PRIMARY]
GO

CREATE INDEX XTKASOLL ON [dbo].[TKALT] ([TKSOLL] ) ON [PRIMARY]
GO

CREATE INDEX XTBARZTNR ON [dbo].[TSEBUCH] ([TBARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XTSKANTRDAT ON [dbo].[TSKKOPF] ([TSKANTRDAT] ) ON [PRIMARY]
GO

CREATE INDEX XTSKDEAKTIV ON [dbo].[TSKKOPF] ([TSKDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XTSKERFDAT ON [dbo].[TSKKOPF] ([TSKERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XTSKERLDAT ON [dbo].[TSKKOPF] ([TSKERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XTSKTYP ON [dbo].[TSKKOPF] ([TSKTYP] ) ON [PRIMARY]
GO

CREATE INDEX XTSKMLERFDAT ON [dbo].[TSKMERKLISTE] ([TSKMLERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XTSKPARZTNR ON [dbo].[TSKPOS] ([TSKPARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XTSKPERFDAT ON [dbo].[TSKPOS] ([TSKPERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XUEDEAKTIV ON [dbo].[UEBERW] ([UEDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XUEERLDAT ON [dbo].[UEBERW] ([UEERLDAT] ) ON [PRIMARY]
GO

CREATE INDEX XUEEXPORTNR ON [dbo].[UEBERW] ([UEEXPORTNR] ) ON [PRIMARY]
GO

CREATE INDEX XUEEDEAKTIV ON [dbo].[UEEMPF] ([UEEDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XUEEEMPFNAME ON [dbo].[UEEMPF] ([UEEEMPFNAME] ) ON [PRIMARY]
GO

CREATE INDEX XVECODE ON [dbo].[VERSICHERUNGEN] ([VECODE] ) ON [PRIMARY]
GO

CREATE INDEX XVACODE ON [dbo].[VETAEMTER] ([VACODE] ) ON [PRIMARY]
GO

CREATE INDEX XVN ON [dbo].[VORNAMEN] ([VVORNAME] ) ON [PRIMARY]
GO

CREATE INDEX XVN2 ON [dbo].[VORNAMEN] ([VVORNAME2] ) ON [PRIMARY]
GO

CREATE INDEX XVODEAKTIV ON [dbo].[VORTRAEGE] ([VODEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XZAARZTNR ON [dbo].[ZAHLUNGEN] ([ZAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZABUCHDAT ON [dbo].[ZAHLUNGEN] ([ZABUCHDAT] ) ON [PRIMARY]
GO

CREATE INDEX XZADEAKTIV ON [dbo].[ZAHLUNGEN] ([ZADEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XZAHALTERARZT ON [dbo].[ZAHLUNGEN] ([ZAHALTERNR],[ZAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZAHALTERNR ON [dbo].[ZAHLUNGEN] ([ZAHALTERNR] ) ON [PRIMARY]
GO

CREATE INDEX XZAPROZNR ON [dbo].[ZAHLUNGEN] ([ZAPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XZARECHARZT ON [dbo].[ZAHLUNGEN] ([ZARECHNR],[ZAARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZARZNR ON [dbo].[ZAHLUNGEN] ([ZARZNR] ) ON [PRIMARY]
GO

CREATE INDEX XZAUEBERWNR ON [dbo].[ZAHLUNGEN] ([ZAUEBERWNR] ) ON [PRIMARY]
GO

CREATE INDEX XZAN ON [dbo].[ZETTEL] ([ZAN] ) ON [PRIMARY]
GO

CREATE INDEX XZART ON [dbo].[ZETTEL] ([ZART] ) ON [PRIMARY]
GO

CREATE INDEX XZARZTNR ON [dbo].[ZETTEL] ([ZARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZDEAKTIV ON [dbo].[ZETTEL] ([ZDEAKTIV] ) ON [PRIMARY]
GO

CREATE INDEX XZERFDAT ON [dbo].[ZETTEL] ([ZERFDAT] ) ON [PRIMARY]
GO

CREATE INDEX XZERLEDIGT ON [dbo].[ZETTEL] ([ZERLEDIGT] ) ON [PRIMARY]
GO

CREATE INDEX XZGUID ON [dbo].[ZETTEL] ([ZGUID] ) ON [PRIMARY]
GO

CREATE INDEX XZHALTERARZT ON [dbo].[ZETTEL] ([ZHALTERNR],[ZARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZPROZNR ON [dbo].[ZETTEL] ([ZPROZNR] ) ON [PRIMARY]
GO

CREATE INDEX XZRECHARZT ON [dbo].[ZETTEL] ([ZRECHNR],[ZARZTNR] ) ON [PRIMARY]
GO

CREATE INDEX XZVON ON [dbo].[ZETTEL] ([ZVON] ) ON [PRIMARY]
GO

CREATE INDEX XZWIEDERVOR ON [dbo].[ZETTEL] ([ZWIEDERVOR] ) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AERZTE]
    ADD CONSTRAINT PK_AERZTE_AARZTNR PRIMARY KEY NONCLUSTERED
      ([AARZTNR]) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[HALTER]
    ADD CONSTRAINT PK_HALTER_HARZTNR_HHALTERNR PRIMARY KEY NONCLUSTERED
      ([HARZTNR],[HHALTERNR]) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LEISTUNGEN]
    ADD CONSTRAINT PK_LEISTUNGEN_LKENN PRIMARY KEY NONCLUSTERED
      ([LKENN]) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RECHKO]
    ADD CONSTRAINT PK_RECHKO_RKARZTNR_RKHALTERNR_RKRECHNR PRIMARY KEY NONCLUSTERED
      ([RKARZTNR],[RKHALTERNR],[RKRECHNR]) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TAKONTO] 
    ADD CONSTRAINT FK_TAKONTO_TKARZTNR
             FOREIGN KEY ([TKARZTNR])
             REFERENCES  [dbo].[AERZTE] 
                         ([AARZTNR])  ON DELETE NO ACTION 
GO

ALTER TABLE [dbo].[ZAHLUNGEN] 
    ADD CONSTRAINT FK_ZAHLUNGEN_ZAARZTNR
             FOREIGN KEY ([ZAARZTNR])
             REFERENCES  [dbo].[AERZTE] 
                         ([AARZTNR])  ON DELETE NO ACTION 
GO

