IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SYSADM')
  exec( 'CREATE SCHEMA [SYSADM] AUTHORIZATION [dbo] ')
GO

CREATE LOGIN [SYSADM] WITH PASSWORD=N'SYSADM', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [SYSADM]
GO

CREATE USER [SYSADM] FOR LOGIN [SYSADM] WITH DEFAULT_SCHEMA=[SYSADM]
GO

ALTER USER [SYSADM] WITH Login = [SYSADM]
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'ALLE')
  exec( 'CREATE SCHEMA [ALLE] AUTHORIZATION [dbo] ')
GO

CREATE Login ALLE with PASSWORD = 'sqlporter' 
GO

CREATE USER ALLE FOR LOGIN ALLE WITH DEFAULT_SCHEMA = ALLE;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'BEVERBUR')
  exec( 'CREATE SCHEMA [BEVERBUR] AUTHORIZATION [dbo] ')
GO

CREATE Login BEVERBUR with PASSWORD = 'sqlporter' 
GO

CREATE USER BEVERBUR FOR LOGIN BEVERBUR WITH DEFAULT_SCHEMA = BEVERBUR;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'FRIEDRIC')
  exec( 'CREATE SCHEMA [FRIEDRIC] AUTHORIZATION [dbo] ')
GO

CREATE Login FRIEDRIC with PASSWORD = 'sqlporter' 
GO

CREATE USER FRIEDRIC FOR LOGIN FRIEDRIC WITH DEFAULT_SCHEMA = FRIEDRIC;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'HENNECKE')
  exec( 'CREATE SCHEMA [HENNECKE] AUTHORIZATION [dbo] ')
GO

CREATE Login HENNECKE with PASSWORD = 'sqlporter' 
GO

CREATE USER HENNECKE FOR LOGIN HENNECKE WITH DEFAULT_SCHEMA = HENNECKE;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'INTENSIO')
  exec( 'CREATE SCHEMA [INTENSIO] AUTHORIZATION [dbo] ')
GO

CREATE Login INTENSIO with PASSWORD = 'sqlporter' 
GO

CREATE USER INTENSIO FOR LOGIN INTENSIO WITH DEFAULT_SCHEMA = INTENSIO;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'KEUER')
  exec( 'CREATE SCHEMA [KEUER] AUTHORIZATION [dbo] ')
GO

CREATE Login KEUER with PASSWORD = 'sqlporter' 
GO

CREATE USER KEUER FOR LOGIN KEUER WITH DEFAULT_SCHEMA = KEUER;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'KOLLAY')
  exec( 'CREATE SCHEMA [KOLLAY] AUTHORIZATION [dbo] ')
GO

CREATE Login KOLLAY with PASSWORD = 'sqlporter' 
GO

CREATE USER KOLLAY FOR LOGIN KOLLAY WITH DEFAULT_SCHEMA = KOLLAY;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'MARTIN')
  exec( 'CREATE SCHEMA [MARTIN] AUTHORIZATION [dbo] ')
GO

CREATE Login MARTIN with PASSWORD = 'sqlporter' 
GO

CREATE USER MARTIN FOR LOGIN MARTIN WITH DEFAULT_SCHEMA = MARTIN;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'ODBC')
  exec( 'CREATE SCHEMA [ODBC] AUTHORIZATION [dbo] ')
GO

CREATE Login ODBC with PASSWORD = 'sqlporter' 
GO

CREATE USER ODBC FOR LOGIN ODBC WITH DEFAULT_SCHEMA = ODBC;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SASSE')
  exec( 'CREATE SCHEMA [SASSE] AUTHORIZATION [dbo] ')
GO

CREATE Login SASSE with PASSWORD = 'sqlporter' 
GO

CREATE USER SASSE FOR LOGIN SASSE WITH DEFAULT_SCHEMA = SASSE;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SC')
  exec( 'CREATE SCHEMA [SC] AUTHORIZATION [dbo] ')
GO

CREATE Login SC with PASSWORD = 'sqlporter' 
GO

CREATE USER SC FOR LOGIN SC WITH DEFAULT_SCHEMA = SC;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SD')
  exec( 'CREATE SCHEMA [SD] AUTHORIZATION [dbo] ')
GO

CREATE Login SD with PASSWORD = 'sqlporter' 
GO

CREATE USER SD FOR LOGIN SD WITH DEFAULT_SCHEMA = SD;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SEIL')
  exec( 'CREATE SCHEMA [SEIL] AUTHORIZATION [dbo] ')
GO

CREATE Login SEIL with PASSWORD = 'sqlporter' 
GO

CREATE USER SEIL FOR LOGIN SEIL WITH DEFAULT_SCHEMA = SEIL;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SQLMON')
  exec( 'CREATE SCHEMA [SQLMON] AUTHORIZATION [dbo] ')
GO

CREATE Login SQLMON with PASSWORD = 'sqlporter' 
GO

CREATE USER SQLMON FOR LOGIN SQLMON WITH DEFAULT_SCHEMA = SQLMON;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'STUKE')
  exec( 'CREATE SCHEMA [STUKE] AUTHORIZATION [dbo] ')
GO

CREATE Login STUKE with PASSWORD = 'sqlporter' 
GO

CREATE USER STUKE FOR LOGIN STUKE WITH DEFAULT_SCHEMA = STUKE;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'SYMOLKA')
  exec( 'CREATE SCHEMA [SYMOLKA] AUTHORIZATION [dbo] ')
GO

CREATE Login SYMOLKA with PASSWORD = 'sqlporter' 
GO

CREATE USER SYMOLKA FOR LOGIN SYMOLKA WITH DEFAULT_SCHEMA = SYMOLKA;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'TIERARZT')
  exec( 'CREATE SCHEMA [TIERARZT] AUTHORIZATION [dbo] ')
GO

CREATE Login TIERARZT with PASSWORD = 'sqlporter' 
GO

CREATE USER TIERARZT FOR LOGIN TIERARZT WITH DEFAULT_SCHEMA = TIERARZT;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'ZINK')
  exec( 'CREATE SCHEMA [ZINK] AUTHORIZATION [dbo] ')
GO

CREATE Login ZINK with PASSWORD = 'sqlporter' 
GO

CREATE USER ZINK FOR LOGIN ZINK WITH DEFAULT_SCHEMA = ZINK;
GO

IF not EXISTS (SELECT * FROM sys.schemas WHERE name = N'ZK')
  exec( 'CREATE SCHEMA [ZK] AUTHORIZATION [dbo] ')
GO

CREATE Login ZK with PASSWORD = 'sqlporter' 
GO

CREATE USER ZK FOR LOGIN ZK WITH DEFAULT_SCHEMA = ZK;
GO

