CREATE SYNONYM dbo.A FOR dbo.AERZTE
GO

CREATE SYNONYM dbo.AA FOR dbo.AERZTEANSPRECH
GO

CREATE SYNONYM dbo.AB FOR dbo.ANWEISUNGSBELEGE
GO

CREATE SYNONYM dbo.AK FOR dbo.AKTIONEN
GO

CREATE SYNONYM dbo.AP FOR dbo.AERZTEPERSONEN
GO

CREATE SYNONYM dbo.AU FOR dbo.AUFSCHLAG
GO

CREATE SYNONYM dbo.AV FOR dbo.ABSCHLVOR
GO

CREATE SYNONYM dbo.BA FOR dbo.BUCHART
GO

CREATE SYNONYM dbo.BB FOR dbo.BATCHBUCH
GO

CREATE SYNONYM dbo.BC FOR dbo.BANKCLEARING
GO

CREATE SYNONYM dbo.BE FOR dbo.BEIHILFEN
GO

CREATE SYNONYM dbo.BEZ FOR dbo.BANKEINZUG
GO

CREATE SYNONYM dbo.BEZD FOR dbo.BEZDATEN
GO

CREATE SYNONYM dbo.BEZS FOR dbo.BEZSTAMM
GO

CREATE SYNONYM dbo.BI FOR dbo.BEHANDLUNGSIDS
GO

CREATE SYNONYM dbo.BLZ FOR dbo.BLZ
GO

CREATE SYNONYM dbo.BN FOR dbo.BENUTZER
GO

CREATE SYNONYM dbo.BP FOR dbo.BATCHPROT
GO

CREATE SYNONYM dbo.BS FOR dbo.BANKENSTAMM
GO

CREATE SYNONYM dbo.BUB FOR dbo.BUCHBEL
GO

CREATE SYNONYM dbo.BZ FOR dbo.BASISZINSEN
GO

CREATE SYNONYM dbo.DB FOR dbo.DBGUIDS
GO

CREATE SYNONYM dbo.DD FOR dbo.DOPPDRUCK
GO

CREATE SYNONYM dbo.DK FOR dbo.DRUKON
GO

CREATE SYNONYM dbo.DL FOR dbo.DRULISTE
GO

CREATE SYNONYM dbo.DS FOR dbo.DATEVSTAMM
GO

CREATE SYNONYM dbo.DU FOR dbo.DUMMY
GO

CREATE SYNONYM dbo.ED FOR dbo.ETIDRU
GO

CREATE SYNONYM dbo.EE FOR dbo.EWAERINNERUNG
GO

CREATE SYNONYM dbo.EL FOR dbo.ERINNERUNGSLISTE
GO

CREATE SYNONYM dbo.EU FOR dbo.EURO
GO

CREATE SYNONYM dbo.EWA FOR dbo.EWA
GO

CREATE SYNONYM dbo.FA FOR dbo.FORDAUFS
GO

CREATE SYNONYM dbo.FE FOR dbo.FEIERTAGE
GO

CREATE SYNONYM dbo.FI FOR dbo.FIBU
GO

CREATE SYNONYM dbo.GE FOR dbo.GERICHTE
GO

CREATE SYNONYM dbo.GL FOR dbo.GELESEN
GO

CREATE SYNONYM dbo.H FOR dbo.HALTER
GO

CREATE SYNONYM dbo.HB FOR dbo.HABU
GO

CREATE SYNONYM dbo.IA FOR dbo.INVAD
GO

CREATE SYNONYM dbo.IK FOR dbo.INVKO
GO

CREATE SYNONYM dbo.INI FOR dbo.INITIALISIERUNG
GO

CREATE SYNONYM dbo.IP FOR dbo.INVPO
GO

CREATE SYNONYM dbo.KO FOR dbo.KONTIERUNGEN
GO

CREATE SYNONYM dbo.L FOR dbo.LEISTUNGEN
GO

CREATE SYNONYM dbo.LB FOR dbo.LOGBUG
GO

CREATE SYNONYM dbo.LC FOR dbo.LAENDERCODES
GO

CREATE SYNONYM dbo.LE FOR dbo.LEISERF
GO

CREATE SYNONYM dbo.LEP FOR dbo.LEISERFPOS
GO

CREATE SYNONYM dbo.LOG FOR dbo.LOG
GO

CREATE SYNONYM dbo.LT FOR dbo.LOESCHTEMP
GO

CREATE SYNONYM dbo.MA FOR dbo.MAHNUNGEN
GO

CREATE SYNONYM dbo.MB FOR dbo.MAHNBESCH
GO

CREATE SYNONYM dbo.MBK FOR dbo.MBKALENDER
GO

CREATE SYNONYM dbo.MBTEMP FOR dbo.MBINFOTEMP
GO

CREATE SYNONYM dbo.MCG FOR dbo.MCGEM
GO

CREATE SYNONYM dbo.MCK FOR dbo.MCKREIS
GO

CREATE SYNONYM dbo.MCL FOR dbo.MCLAND
GO

CREATE SYNONYM dbo.MCO FOR dbo.MCORT
GO

CREATE SYNONYM dbo.MCOT FOR dbo.MCORTT
GO

CREATE SYNONYM dbo.MCP FOR dbo.MCPLZ
GO

CREATE SYNONYM dbo.MCS FOR dbo.MCSTR
GO

CREATE SYNONYM dbo.MD FOR dbo.MAHNDATEN
GO

CREATE SYNONYM dbo.MG FOR dbo.MAHNGEB
GO

CREATE SYNONYM dbo.MI FOR dbo.MAHNINT
GO

CREATE SYNONYM dbo.MK FOR dbo.MBKOSTEN
GO

CREATE SYNONYM dbo.MT FOR dbo.MAHNTEXTE
GO

CREATE SYNONYM dbo.MV FOR dbo.MAHNVOR
GO

CREATE SYNONYM dbo.NR FOR dbo.NUMMERN
GO

CREATE SYNONYM dbo.PE FOR dbo.PERSONEN
GO

CREATE SYNONYM dbo.PI FOR dbo.PACKINFO
GO

CREATE SYNONYM dbo.PN FOR dbo.PEGASUSNUTZUNG
GO

CREATE SYNONYM dbo.PND FOR dbo.PEGASUSNUTZUNGDATEN
GO

CREATE SYNONYM dbo.PR FOR dbo.PROZREG
GO

CREATE SYNONYM dbo.PRD FOR dbo.PROZREGDET
GO

CREATE SYNONYM dbo.PRE FOR dbo.PREDA
GO

CREATE SYNONYM dbo.PRID FOR dbo.PRINTIDS
GO

CREATE SYNONYM dbo.R FOR dbo.RATEN
GO

CREATE SYNONYM dbo.RA FOR dbo.RECHAB
GO

CREATE SYNONYM dbo.RB FOR dbo.RECHBUCH
GO

CREATE SYNONYM dbo.RE FOR dbo.RUECKERST
GO

CREATE SYNONYM dbo.RI FOR dbo.RISER
GO

CREATE SYNONYM dbo.RK FOR dbo.RECHKO
GO

CREATE SYNONYM dbo.RP FOR dbo.RECHPO
GO

CREATE SYNONYM dbo.RR FOR dbo.RUECKRUF
GO

CREATE SYNONYM dbo.RT FOR dbo.RECHTEXTE
GO

CREATE SYNONYM dbo.RZ FOR dbo.RAZA
GO

CREATE SYNONYM dbo.RZP FOR dbo.RAZAPOS
GO

CREATE SYNONYM dbo.SB FOR dbo.STEUERBERATER
GO

CREATE SYNONYM dbo.SL FOR dbo.SUPPORTLOG
GO

CREATE SYNONYM dbo.SP FOR dbo.SPERREN
GO

CREATE SYNONYM dbo.ST FOR dbo.STAFFELN
GO

CREATE SYNONYM dbo.TB FOR dbo.TSEBUCH
GO

CREATE SYNONYM dbo.TDE FOR dbo.TEMPDATEURO
GO

CREATE SYNONYM dbo.TE FOR dbo.TELEFON
GO

CREATE SYNONYM dbo.TK FOR dbo.TAKONTO
GO

CREATE SYNONYM dbo.TKA FOR dbo.TKALT
GO

CREATE SYNONYM dbo.TKALT FOR dbo.TKALT
GO

CREATE SYNONYM dbo.TSK FOR dbo.TSKKOPF
GO

CREATE SYNONYM dbo.TSKML FOR dbo.TSKMERKLISTE
GO

CREATE SYNONYM dbo.TSKP FOR dbo.TSKPOS
GO

CREATE SYNONYM dbo.UE FOR dbo.UEBERW
GO

CREATE SYNONYM dbo.UEE FOR dbo.UEEMPF
GO

CREATE SYNONYM dbo.UF FOR dbo.UEBFIBU
GO

CREATE SYNONYM dbo.V FOR dbo.VERMERKE
GO

CREATE SYNONYM dbo.VA FOR dbo.VETAEMTER
GO

CREATE SYNONYM dbo.VE FOR dbo.VERSICHERUNGEN
GO

CREATE SYNONYM dbo.VN FOR dbo.VORNAMEN
GO

CREATE SYNONYM dbo.VO FOR dbo.VORTRAEGE
GO

CREATE SYNONYM dbo.Z FOR dbo.ZETTEL
GO

CREATE SYNONYM dbo.ZA FOR dbo.ZAHLUNGEN
GO

CREATE SYNONYM dbo.ZU FOR dbo.ZUSTAENDIGKEITEN
GO

CREATE SYNONYM dbo.FA FOR dbo.FORDAUFS
GO

