// <ppj name="Moveta.Intern" date="1/29/2024 3:39:48 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class dlgBEZRetoure
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// Client area panel.
		/// </summary>
		protected SalFormClientArea ClientArea;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		protected SalBackgroundText bkgdRetoureNr;
		protected SalBackgroundText bkgd1;
		public SalDataField dfArztNr;
		public SalDataField dfArztName;
		protected SalBackgroundText bkgd2;
		public SalDataField dfHalterNr;
		public SalDataField dfHalterName;
		protected SalBackgroundText bkgd3;
		public SalDataField dfRechnungNr;
		protected SalBackgroundText bkgd3b;
		public SalDataField dfBelegNr;
		protected SalBackgroundText bkgd4;
		public SalDataField dfEinzug;
		protected SalBackgroundText bkgd5;
		public SalDataField dfGebuehren;
		public SalPushbutton pbOk;
		public SalRadioButton rb1;
		public SalRadioButton rb2;
		protected SalGroupBox grp1;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.ClientArea = new PPJ.Runtime.Windows.SalFormClientArea();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.bkgdRetoureNr = new PPJ.Runtime.Windows.SalBackgroundText();
			this.bkgd1 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfArztNr = new PPJ.Runtime.Windows.SalDataField();
			this.dfArztName = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd2 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfHalterNr = new PPJ.Runtime.Windows.SalDataField();
			this.dfHalterName = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd3 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfRechnungNr = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd3b = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfBelegNr = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd4 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfEinzug = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd5 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfGebuehren = new PPJ.Runtime.Windows.SalDataField();
			this.pbOk = new PPJ.Runtime.Windows.SalPushbutton();
			this.rb1 = new PPJ.Runtime.Windows.SalRadioButton();
			this.rb2 = new PPJ.Runtime.Windows.SalRadioButton();
			this.grp1 = new PPJ.Runtime.Windows.SalGroupBox();
			this.ToolBar.SuspendLayout();
			this.ClientArea.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// ClientArea
			// 
			this.ClientArea.Name = "ClientArea";
			this.ClientArea.AutoScroll = false;
			this.ClientArea.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.ClientArea.Controls.Add(this.rb2);
			this.ClientArea.Controls.Add(this.rb1);
			this.ClientArea.Controls.Add(this.pbOk);
			this.ClientArea.Controls.Add(this.dfGebuehren);
			this.ClientArea.Controls.Add(this.dfEinzug);
			this.ClientArea.Controls.Add(this.dfBelegNr);
			this.ClientArea.Controls.Add(this.dfRechnungNr);
			this.ClientArea.Controls.Add(this.dfHalterName);
			this.ClientArea.Controls.Add(this.dfHalterNr);
			this.ClientArea.Controls.Add(this.dfArztName);
			this.ClientArea.Controls.Add(this.dfArztNr);
			this.ClientArea.Controls.Add(this.bkgd5);
			this.ClientArea.Controls.Add(this.bkgd4);
			this.ClientArea.Controls.Add(this.bkgd3b);
			this.ClientArea.Controls.Add(this.bkgd3);
			this.ClientArea.Controls.Add(this.bkgd2);
			this.ClientArea.Controls.Add(this.bkgd1);
			this.ClientArea.Controls.Add(this.bkgdRetoureNr);
			this.ClientArea.Controls.Add(this.grp1);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// bkgdRetoureNr
			// 
			this.bkgdRetoureNr.Name = "bkgdRetoureNr";
			this.bkgdRetoureNr.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Bold);
			this.bkgdRetoureNr.Text = "";
			this.bkgdRetoureNr.Location = new System.Drawing.Point(15, 11);
			this.bkgdRetoureNr.Size = new System.Drawing.Size(640, 20);
			this.bkgdRetoureNr.TabIndex = 0;
			// 
			// bkgd1
			// 
			this.bkgd1.Name = "bkgd1";
			this.bkgd1.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd1.Text = "Mitglied Nr.";
			this.bkgd1.Location = new System.Drawing.Point(15, 41);
			this.bkgd1.Size = new System.Drawing.Size(80, 20);
			this.bkgd1.TabIndex = 1;
			// 
			// dfArztNr
			// 
			this.dfArztNr.Name = "dfArztNr";
			this.dfArztNr.BackColor = System.Drawing.Color.White;
			this.dfArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfArztNr.ReadOnly = true;
			this.dfArztNr.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfArztNr.Location = new System.Drawing.Point(127, 39);
			this.dfArztNr.Size = new System.Drawing.Size(64, 30);
			this.dfArztNr.TabIndex = 2;
			// 
			// dfArztName
			// 
			this.dfArztName.Name = "dfArztName";
			this.dfArztName.BackColor = System.Drawing.Color.White;
			this.dfArztName.ReadOnly = true;
			this.dfArztName.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfArztName.Location = new System.Drawing.Point(223, 39);
			this.dfArztName.Size = new System.Drawing.Size(464, 30);
			this.dfArztName.TabIndex = 3;
			// 
			// bkgd2
			// 
			this.bkgd2.Name = "bkgd2";
			this.bkgd2.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd2.Text = "Halter Nr.";
			this.bkgd2.Location = new System.Drawing.Point(15, 71);
			this.bkgd2.Size = new System.Drawing.Size(80, 20);
			this.bkgd2.TabIndex = 4;
			// 
			// dfHalterNr
			// 
			this.dfHalterNr.Name = "dfHalterNr";
			this.dfHalterNr.BackColor = System.Drawing.Color.White;
			this.dfHalterNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfHalterNr.ReadOnly = true;
			this.dfHalterNr.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfHalterNr.Location = new System.Drawing.Point(127, 69);
			this.dfHalterNr.Size = new System.Drawing.Size(64, 30);
			this.dfHalterNr.TabIndex = 5;
			// 
			// dfHalterName
			// 
			this.dfHalterName.Name = "dfHalterName";
			this.dfHalterName.BackColor = System.Drawing.Color.White;
			this.dfHalterName.ReadOnly = true;
			this.dfHalterName.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfHalterName.Location = new System.Drawing.Point(223, 69);
			this.dfHalterName.Size = new System.Drawing.Size(464, 30);
			this.dfHalterName.TabIndex = 6;
			// 
			// bkgd3
			// 
			this.bkgd3.Name = "bkgd3";
			this.bkgd3.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd3.Text = "Rechnung Nr.";
			this.bkgd3.Location = new System.Drawing.Point(15, 101);
			this.bkgd3.Size = new System.Drawing.Size(80, 20);
			this.bkgd3.TabIndex = 7;
			// 
			// dfRechnungNr
			// 
			this.dfRechnungNr.Name = "dfRechnungNr";
			this.dfRechnungNr.BackColor = System.Drawing.Color.White;
			this.dfRechnungNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfRechnungNr.ReadOnly = true;
			this.dfRechnungNr.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfRechnungNr.Format = "#0";
			this.dfRechnungNr.Location = new System.Drawing.Point(127, 99);
			this.dfRechnungNr.Size = new System.Drawing.Size(64, 30);
			this.dfRechnungNr.TabIndex = 8;
			// 
			// bkgd3b
			// 
			this.bkgd3b.Name = "bkgd3b";
			this.bkgd3b.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd3b.Text = "Beleg Nr.";
			this.bkgd3b.Location = new System.Drawing.Point(15, 131);
			this.bkgd3b.Size = new System.Drawing.Size(80, 20);
			this.bkgd3b.TabIndex = 9;
			// 
			// dfBelegNr
			// 
			this.dfBelegNr.Name = "dfBelegNr";
			this.dfBelegNr.BackColor = System.Drawing.Color.White;
			this.dfBelegNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfBelegNr.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfBelegNr.Format = "#0";
			this.dfBelegNr.Location = new System.Drawing.Point(127, 129);
			this.dfBelegNr.Size = new System.Drawing.Size(64, 30);
			this.dfBelegNr.TabIndex = 10;
			// 
			// bkgd4
			// 
			this.bkgd4.Name = "bkgd4";
			this.bkgd4.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd4.Text = "Nächster Einzug";
			this.bkgd4.Location = new System.Drawing.Point(15, 161);
			this.bkgd4.Size = new System.Drawing.Size(112, 20);
			this.bkgd4.TabIndex = 11;
			// 
			// dfEinzug
			// 
			this.dfEinzug.Name = "dfEinzug";
			this.dfEinzug.BackColor = System.Drawing.Color.White;
			this.dfEinzug.DataType = PPJ.Runtime.Windows.DataType.DateTime;
			this.dfEinzug.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfEinzug.Format = "dd.MM.yyyy";
			this.dfEinzug.Location = new System.Drawing.Point(127, 159);
			this.dfEinzug.Size = new System.Drawing.Size(80, 30);
			this.dfEinzug.TabIndex = 12;
			// 
			// bkgd5
			// 
			this.bkgd5.Name = "bkgd5";
			this.bkgd5.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd5.Text = "Gebühren €";
			this.bkgd5.Location = new System.Drawing.Point(15, 191);
			this.bkgd5.Size = new System.Drawing.Size(80, 20);
			this.bkgd5.TabIndex = 13;
			// 
			// dfGebuehren
			// 
			this.dfGebuehren.Name = "dfGebuehren";
			this.dfGebuehren.BackColor = System.Drawing.Color.White;
			this.dfGebuehren.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfGebuehren.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfGebuehren.Format = "#0.00";
			this.dfGebuehren.Location = new System.Drawing.Point(127, 189);
			this.dfGebuehren.Size = new System.Drawing.Size(80, 30);
			this.dfGebuehren.TabIndex = 14;
			// 
			// pbOk
			// 
			this.pbOk.Name = "pbOk";
			this.pbOk.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbOk.Text = "Retoure buchen";
			this.pbOk.Location = new System.Drawing.Point(223, 199);
			this.pbOk.Size = new System.Drawing.Size(464, 65);
			this.pbOk.Image = global::Moveta.Intern.Properties.Resources.ok;
			this.pbOk.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbOk.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbOk_WindowActions);
			this.pbOk.TabIndex = 15;
			// 
			// rb1
			// 
			this.rb1.Name = "rb1";
			this.rb1.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rb1.Text = "fehlender Deckung";
			this.rb1.Location = new System.Drawing.Point(239, 139);
			this.rb1.Size = new System.Drawing.Size(168, 30);
			this.rb1.TabIndex = 16;
			// 
			// rb2
			// 
			this.rb2.Name = "rb2";
			this.rb2.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rb2.Text = "Kontolöschung";
			this.rb2.Location = new System.Drawing.Point(383, 139);
			this.rb2.Size = new System.Drawing.Size(168, 30);
			this.rb2.TabIndex = 17;
			// 
			// grp1
			// 
			this.grp1.Name = "grp1";
			this.grp1.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Regular);
			this.grp1.Text = "Retoure wegen";
			this.grp1.Location = new System.Drawing.Point(223, 119);
			this.grp1.Size = new System.Drawing.Size(464, 60);
			this.grp1.TabIndex = 18;
			// 
			// dlgBEZRetoure
			// 
			this.Controls.Add(this.ClientArea);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "dlgBEZRetoure";
			this.ClientSize = new System.Drawing.Size(716, 310);
			this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultLocation;
			this.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Regular);
			this.Text = "BEZ-Retoure";
			this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.dlgBEZRetoure_WindowActions);
			this.ToolBar.ResumeLayout(false);
			this.ClientArea.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.dlgBEZRetoure == this) 
			{
				App.dlgBEZRetoure = null;
			}
			base.Dispose(disposing);
		}
		#endregion
	}
}
