// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	/// <summary>
	/// </summary>
	/// <param name="strS1"></param>
	/// <param name="strS2"></param>
	/// <param name="strS3"></param>
	/// <param name="strS4"></param>
	/// <param name="strS5"></param>
	/// <param name="strNeuKenn"></param>
	/// <param name="nLen"></param>
	/// <param name="strParent"></param>
	public partial class dlgEinStringScan : SalDialogBox
	{
		#region Window Parameters
		public SalString strS1;
		public SalString strS2;
		public SalString strS3;
		public SalString strS4;
		public SalString strS5;
		public SalString strNeuKenn;
		public SalNumber nLen;
		public SalString strParent;
		#endregion
		
		#region Window Variables
		public SalNumber nColor = 0;
		#endregion
		
		#region Constructors/Destructors
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public dlgEinStringScan(SalString strS1, SalString strS2, SalString strS3, SalString strS4, SalString strS5, SalString strNeuKenn, SalNumber nLen, SalString strParent)
		{
			// Assign global reference.
			App.dlgEinStringScan = this;
			// Window Parameters initialization.
			this.strS1 = strS1;
			this.strS2 = strS2;
			this.strS3 = strS3;
			this.strS4 = strS4;
			this.strS5 = strS5;
			this.strNeuKenn = strNeuKenn;
			this.nLen = nLen;
			this.strParent = strParent;
			// This call is required by the Windows Form Designer.
			InitializeComponent();
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Shows the modal dialog.
		/// </summary>
		/// <param name="owner"></param>
		/// <returns></returns>
		public static SalNumber ModalDialog(Control owner, SalString strS1, SalString strS2, SalString strS3, SalString strS4, SalString strS5, ref SalString strNeuKenn, SalNumber nLen, SalString strParent)
		{
			dlgEinStringScan dlg = new dlgEinStringScan(strS1, strS2, strS3, strS4, strS5, strNeuKenn, nLen, strParent);
			SalNumber ret = dlg.ShowDialog(owner);
			strNeuKenn = dlg.strNeuKenn;
			return ret;
		}
		
		/// <summary>
		/// Returns the object instance associated with the window handle.
		/// </summary>
		/// <param name="handle"></param>
		/// <returns></returns>
		[DebuggerStepThrough]
		public static dlgEinStringScan FromHandle(SalWindowHandle handle)
		{
			return ((dlgEinStringScan)SalWindow.FromHandle(handle, typeof(dlgEinStringScan)));
		}
		#endregion
		
		#region Window Actions
		
		/// <summary>
		/// dlgEinStringScan WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dlgEinStringScan_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Create:
					this.dlgEinStringScan_OnSAM_Create(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dlgEinStringScan_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			this.nColor = this.GetWindowColor(Sys.COLOR_IndexWindow);
			this.dfS1.SetWindowColor(Sys.COLOR_IndexWindow, this.nColor);
			this.dfS2.SetWindowColor(Sys.COLOR_IndexWindow, this.nColor);
			this.dfS3.SetWindowColor(Sys.COLOR_IndexWindow, this.nColor);
			this.dfS4.SetWindowColor(Sys.COLOR_IndexWindow, this.nColor);
			this.dfS5.SetWindowColor(Sys.COLOR_IndexWindow, this.nColor);
			// 04.02.02
			this.dfKenn.SetDataLength(this.nLen);
			this.cmbSchlagwort.SetDataLength(this.nLen);
			this.dfS1.Text = this.strS1;
			this.dfS2.Text = this.strS2;
			this.dfS3.Text = this.strS3;
			this.dfS4.Text = this.strS4;
			this.dfS5.Text = this.strS5;
			// 04.11.21
			this.dfKenn.HideWindow();
			if (this.strParent == "ScanPR") 
			{
				this.cmbSchlagwort.HideWindow();
				this.cmbSchlagwort.Text = this.strNeuKenn;
			}
			else
			{
				this.cmbSchlagwortPR.HideWindow();
				this.dfKenn.Text = this.strNeuKenn;
			}

			Sal.WaitCursor(false);
			#endregion
		}
		
		/// <summary>
		/// pbOk2 WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbOk2_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbOk2_OnSAM_Click(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbOk2_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// 04.11.21
			if (this.strParent == "ScanPR") 
			{
				this.dfKenn.Text = this.cmbSchlagwortPR.Text;
			}
			else
			{
				this.dfKenn.Text = this.cmbSchlagwort.Text;
			}

			if (this.dfKenn.Text == "") 
			{
				Sal.MessageBox("Bitte wählen Sie ein Schlagwort.", "Achtung", Sys.MB_Ok);
			}
			else
			{
				this.strNeuKenn = this.dfKenn.Text;
				this.EndDialog(1);
			}
			#endregion
		}
		
		/// <summary>
		/// dfKenn WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dfKenn_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Validate:
					this.dfKenn_OnSAM_Validate(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Validate event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void dfKenn_OnSAM_Validate(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// 03.09.19 F4525
			if (this.strParent == "Scan") 
			{
				this.dfKenn.Text = Int.PalDelZeichen(this.dfKenn.Text, "\\\\");
				this.dfKenn.Text = Int.PalDelZeichen(this.dfKenn.Text, "\\%");
				this.dfKenn.Text = Int.PalDelZeichen(this.dfKenn.Text, "/");
			}
			#endregion
		}
		
		/// <summary>
		/// pbAbbruch WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbAbbruch_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbAbbruch_OnSAM_Click(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbAbbruch_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// Call SalDestroyWindow (hWndForm)
			this.SendMessage(Sys.SAM_Close, 0, 0);
			#endregion
		}
		#endregion
	}
}
