// <ppj name="Moveta.Intern" date="1/29/2024 3:39:48 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class dlgPWChange
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// Client area panel.
		/// </summary>
		protected SalFormClientArea ClientArea;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		protected SalBackgroundText bkgd3;
		public SalDataField dfPWa;
		protected SalBackgroundText bkgd4;
		public SalDataField dfPWn;
		protected SalBackgroundText bkgd5;
		public SalDataField dfPWn2;
		public SalPushbutton pbOk;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.ClientArea = new PPJ.Runtime.Windows.SalFormClientArea();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.bkgd3 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfPWa = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd4 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfPWn = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd5 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfPWn2 = new PPJ.Runtime.Windows.SalDataField();
			this.pbOk = new PPJ.Runtime.Windows.SalPushbutton();
			this.ToolBar.SuspendLayout();
			this.ClientArea.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// ClientArea
			// 
			this.ClientArea.Name = "ClientArea";
			this.ClientArea.AutoScroll = false;
			this.ClientArea.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.ClientArea.Controls.Add(this.pbOk);
			this.ClientArea.Controls.Add(this.dfPWn2);
			this.ClientArea.Controls.Add(this.dfPWn);
			this.ClientArea.Controls.Add(this.dfPWa);
			this.ClientArea.Controls.Add(this.bkgd5);
			this.ClientArea.Controls.Add(this.bkgd4);
			this.ClientArea.Controls.Add(this.bkgd3);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// bkgd3
			// 
			this.bkgd3.Name = "bkgd3";
			this.bkgd3.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd3.Text = "Altes Paßwort:";
			this.bkgd3.Location = new System.Drawing.Point(23, 21);
			this.bkgd3.Size = new System.Drawing.Size(128, 20);
			this.bkgd3.TabIndex = 0;
			// 
			// dfPWa
			// 
			this.dfPWa.Name = "dfPWa";
			this.dfPWa.BackColor = System.Drawing.Color.White;
			this.dfPWa.MaxLength = 8;
			this.dfPWa.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfPWa.Format = "";
			this.dfPWa.PasswordChar = '*';
			this.dfPWa.Location = new System.Drawing.Point(159, 19);
			this.dfPWa.Size = new System.Drawing.Size(152, 30);
			this.dfPWa.TabIndex = 1;
			// 
			// bkgd4
			// 
			this.bkgd4.Name = "bkgd4";
			this.bkgd4.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd4.Text = "Neues Paßwort:";
			this.bkgd4.Location = new System.Drawing.Point(23, 61);
			this.bkgd4.Size = new System.Drawing.Size(128, 20);
			this.bkgd4.TabIndex = 2;
			// 
			// dfPWn
			// 
			this.dfPWn.Name = "dfPWn";
			this.dfPWn.BackColor = System.Drawing.Color.White;
			this.dfPWn.MaxLength = 8;
			this.dfPWn.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfPWn.Format = "";
			this.dfPWn.PasswordChar = '*';
			this.dfPWn.Location = new System.Drawing.Point(159, 59);
			this.dfPWn.Size = new System.Drawing.Size(152, 30);
			this.dfPWn.TabIndex = 3;
			// 
			// bkgd5
			// 
			this.bkgd5.Name = "bkgd5";
			this.bkgd5.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd5.Text = "Wiederholung:";
			this.bkgd5.Location = new System.Drawing.Point(23, 101);
			this.bkgd5.Size = new System.Drawing.Size(128, 20);
			this.bkgd5.TabIndex = 4;
			// 
			// dfPWn2
			// 
			this.dfPWn2.Name = "dfPWn2";
			this.dfPWn2.BackColor = System.Drawing.Color.White;
			this.dfPWn2.MaxLength = 8;
			this.dfPWn2.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfPWn2.Format = "";
			this.dfPWn2.PasswordChar = '*';
			this.dfPWn2.Location = new System.Drawing.Point(159, 99);
			this.dfPWn2.Size = new System.Drawing.Size(152, 30);
			this.dfPWn2.TabIndex = 5;
			// 
			// pbOk
			// 
			this.pbOk.Name = "pbOk";
			this.pbOk.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbOk.Text = "&Ok";
			this.pbOk.Location = new System.Drawing.Point(159, 139);
			this.pbOk.Size = new System.Drawing.Size(152, 60);
			this.pbOk.Image = global::Moveta.Intern.Properties.Resources.ok;
			this.pbOk.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbOk.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbOk_WindowActions);
			this.pbOk.TabIndex = 6;
			// 
			// dlgPWChange
			// 
			this.Controls.Add(this.ClientArea);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "dlgPWChange";
			this.ClientSize = new System.Drawing.Size(338, 232);
			this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultLocation;
			this.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Regular);
			this.Text = "Paßwort ändern";
			this.ToolBar.ResumeLayout(false);
			this.ClientArea.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.dlgPWChange == this) 
			{
				App.dlgPWChange = null;
			}
			base.Dispose(disposing);
		}
		#endregion
	}
}
