// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class frmFiBu
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// Client area panel.
		/// </summary>
		protected SalFormClientArea ClientArea;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		// Text: 1 - Verarbeiten Rechng. / Mahnungen
		// Text: 2 - Zahlungen der Halter
		// Text: 2a - Retouren
		// Text: 3 - Zahlungen ausbatchen
		// Text: 4 - Rechnungen ausbuchen
		// Text: 4a - Ausbuchung rückgängig machen
		// Text: 5 - sonst. Buchungen
		// Text: 6 - Buchen MB-Kosten
		// Text: 7 - Bank-Clearing
		// Text: 8 - Buchungskontrolle
		// Text: 8a- TA-Konto durchsuchen
		// Text: 8 - Drucken
		// Text: 9a- Übergaben sperren
		// Text: 9b- Monatsabschluß
		// Text: 9c- Übergaben erlauben
		// Text: --------------------------------------------------------
		// Text: A - Abschlags-Vorschlag erstellen
		// Text: B - Abschläge ändern
		// Text: C - Bank-Datei erstellen + Übergabe FiBu
		// Text: --------------------------------------------------------
		// Text: D - Steuerberaterdatei erstellen
		// Text: --------------------------------------------------------
		// Text: M - Myco - Pfizer-Rechnung
		// Text: X - Beiträge und Einlagen automatisch buchen
		public SalListBox lbFiBuAktionen;
		public SalDataField dfSperre;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.ClientArea = new PPJ.Runtime.Windows.SalFormClientArea();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.lbFiBuAktionen = new PPJ.Runtime.Windows.SalListBox();
			this.dfSperre = new PPJ.Runtime.Windows.SalDataField();
			this.ToolBar.SuspendLayout();
			this.ClientArea.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// ClientArea
			// 
			this.ClientArea.Name = "ClientArea";
			this.ClientArea.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.ClientArea.Controls.Add(this.dfSperre);
			this.ClientArea.Controls.Add(this.lbFiBuAktionen);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// lbFiBuAktionen
			// 
			this.lbFiBuAktionen.Name = "lbFiBuAktionen";
			this.lbFiBuAktionen.HorizontalScrollbar = false;
			this.lbFiBuAktionen.BackColor = System.Drawing.Color.White;
			this.lbFiBuAktionen.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Regular);
			this.lbFiBuAktionen.SelectionMode = System.Windows.Forms.SelectionMode.One;
			this.lbFiBuAktionen.Sorted = false;
			this.lbFiBuAktionen.Location = new System.Drawing.Point(23, 23);
			this.lbFiBuAktionen.Size = new System.Drawing.Size(342, 422);
			this.lbFiBuAktionen.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.lbFiBuAktionen_WindowActions);
			this.lbFiBuAktionen.TabIndex = 0;
			// 
			// dfSperre
			// 
			this.dfSperre.Name = "dfSperre";
			this.dfSperre.BackColor = System.Drawing.Color.White;
			this.dfSperre.ReadOnly = true;
			this.dfSperre.Font = new Font("Tahoma", 12f, System.Drawing.FontStyle.Regular);
			this.dfSperre.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
			this.dfSperre.Location = new System.Drawing.Point(23, 455);
			this.dfSperre.Size = new System.Drawing.Size(342, 24);
			this.dfSperre.TabIndex = 1;
			// 
			// frmFiBu
			// 
			this.Controls.Add(this.ClientArea);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "frmFiBu";
			this.ClientSize = new System.Drawing.Size(393, 521);
			this.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.IconName = "abrdisk.ico";
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.ForeColor = System.Drawing.SystemColors.WindowText;
			this.Text = "Buchhaltung";
			this.Location = new System.Drawing.Point(143, 34);
			this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
			this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.frmFiBu_WindowActions);
			this.ToolBar.ResumeLayout(false);
			this.ClientArea.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.frmFiBu == this) 
			{
				App.frmFiBu = null;
			}
			base.Dispose(disposing);
		}
		#endregion
	}
}
