// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class frmJahresSummen
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// Client area panel.
		/// </summary>
		protected SalFormClientArea ClientArea;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		public frmJahresSummen.tblJSTableWindow tblJS;
		public SalListBox lbPrinters;
		public SalPushbutton pbDruck;
		public SalOptionButton obExcel;
		public SalOptionButton obOO;
		public SalPushbutton pbExport;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.ClientArea = new PPJ.Runtime.Windows.SalFormClientArea();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.tblJS = (frmJahresSummen.tblJSTableWindow)CreateTableWindow(typeof(frmJahresSummen.tblJSTableWindow));
			this.lbPrinters = new PPJ.Runtime.Windows.SalListBox();
			this.pbDruck = new PPJ.Runtime.Windows.SalPushbutton();
			this.obExcel = new PPJ.Runtime.Windows.SalOptionButton();
			this.obOO = new PPJ.Runtime.Windows.SalOptionButton();
			this.pbExport = new PPJ.Runtime.Windows.SalPushbutton();
			this.ToolBar.SuspendLayout();
			this.ClientArea.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// ClientArea
			// 
			this.ClientArea.Name = "ClientArea";
			this.ClientArea.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.ClientArea.Controls.Add(this.pbExport);
			this.ClientArea.Controls.Add(this.obOO);
			this.ClientArea.Controls.Add(this.obExcel);
			this.ClientArea.Controls.Add(this.pbDruck);
			this.ClientArea.Controls.Add(this.lbPrinters);
			this.ClientArea.Controls.Add(this.tblJS);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// tblJS
			// 
			this.tblJS.Name = "tblJS";
			this.tblJS.BackColor = System.Drawing.Color.White;
			this.tblJS.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.tblJS.Location = new System.Drawing.Point(17, 7);
			this.tblJS.Size = new System.Drawing.Size(792, 312);
			this.tblJS.UseVisualStyles = true;
			// 
			// tblJS.colBez
			// 
			this.tblJS.colBez.Name = "colBez";
			this.tblJS.colBez.Title = "Bezeichnung";
			this.tblJS.colBez.Width = 213;
			this.tblJS.colBez.Position = 1;
			// 
			// tblJS.colJahr1
			// 
			this.tblJS.colJahr1.Name = "colJahr1";
			this.tblJS.colJahr1.Title = "(Untitled)";
			this.tblJS.colJahr1.Width = 173;
			this.tblJS.colJahr1.Enabled = false;
			this.tblJS.colJahr1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblJS.colJahr1.Position = 2;
			// 
			// tblJS.colJahr2
			// 
			this.tblJS.colJahr2.Name = "colJahr2";
			this.tblJS.colJahr2.Title = "(Untitled)";
			this.tblJS.colJahr2.Width = 173;
			this.tblJS.colJahr2.Enabled = false;
			this.tblJS.colJahr2.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblJS.colJahr2.Position = 3;
			// 
			// tblJS.colJahr3
			// 
			this.tblJS.colJahr3.Name = "colJahr3";
			this.tblJS.colJahr3.Title = "(Untitled)";
			this.tblJS.colJahr3.Width = 173;
			this.tblJS.colJahr3.Enabled = false;
			this.tblJS.colJahr3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblJS.colJahr3.Position = 4;
			this.tblJS.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.tblJS_WindowActions);
			this.tblJS.TabIndex = 0;
			// 
			// lbPrinters
			// 
			this.lbPrinters.Name = "lbPrinters";
			this.lbPrinters.HorizontalScrollbar = false;
			this.lbPrinters.BackColor = System.Drawing.Color.White;
			this.lbPrinters.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.lbPrinters.SelectionMode = System.Windows.Forms.SelectionMode.One;
			this.lbPrinters.Sorted = true;
			this.lbPrinters.Location = new System.Drawing.Point(17, 327);
			this.lbPrinters.Size = new System.Drawing.Size(565, 84);
			this.lbPrinters.TabIndex = 1;
			// 
			// pbDruck
			// 
			this.pbDruck.Name = "pbDruck";
			this.pbDruck.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbDruck.Text = "Tabelle";
			this.pbDruck.Location = new System.Drawing.Point(591, 327);
			this.pbDruck.Size = new System.Drawing.Size(72, 56);
			this.pbDruck.TransparentColor = System.Drawing.Color.White;
			this.pbDruck.Image = global::Moveta.Intern.Properties.Resources.printer2;
			this.pbDruck.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbDruck.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbDruck_WindowActions);
			this.pbDruck.TabIndex = 2;
			// 
			// obExcel
			// 
			this.obExcel.Name = "obExcel";
			this.obExcel.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.obExcel.Text = "Excel";
			this.obExcel.Location = new System.Drawing.Point(672, 327);
			this.obExcel.Size = new System.Drawing.Size(92, 28);
			this.obExcel.ButtonStyle = PPJ.Runtime.Windows.OptionButtonStyle.Radio;
			this.obExcel.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.obExcel.TabIndex = 3;
			// 
			// obOO
			// 
			this.obOO.Name = "obOO";
			this.obOO.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.obOO.Text = "Open Office";
			this.obOO.Location = new System.Drawing.Point(672, 355);
			this.obOO.Size = new System.Drawing.Size(92, 28);
			this.obOO.ButtonStyle = PPJ.Runtime.Windows.OptionButtonStyle.Radio;
			this.obOO.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.obOO.TabIndex = 4;
			// 
			// pbExport
			// 
			this.pbExport.Name = "pbExport";
			this.pbExport.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbExport.Location = new System.Drawing.Point(765, 327);
			this.pbExport.Size = new System.Drawing.Size(41, 56);
			this.pbExport.TransparentColor = System.Drawing.Color.White;
			this.pbExport.Image = global::Moveta.Intern.Properties.Resources.export;
			this.pbExport.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbExport.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbExport_WindowActions);
			this.pbExport.TabIndex = 5;
			// 
			// frmJahresSummen
			// 
			this.Controls.Add(this.ClientArea);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "frmJahresSummen";
			this.ClientSize = new System.Drawing.Size(854, 464);
			this.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.ForeColor = System.Drawing.SystemColors.WindowText;
			this.Text = "Jahressummen";
			this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.frmJahresSummen_WindowActions);
			this.ToolBar.ResumeLayout(false);
			this.ClientArea.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.frmJahresSummen == this) 
			{
				App.frmJahresSummen = null;
			}
			base.Dispose(disposing);
		}
		#endregion
		
		#region tblJS
		
		public partial class tblJSTableWindow
		{
			#region Window Controls
			public SalTableColumn colBez;
			public SalTableColumn colJahr1;
			public SalTableColumn colJahr2;
			public SalTableColumn colJahr3;
			#endregion
			
			#region Windows Form Designer generated code
			
			/// <summary>
			/// Required method for Designer support - do not modify
			/// the contents of this method with the code editor.
			/// </summary>
			private void InitializeComponent()
			{
				this.colBez = new PPJ.Runtime.Windows.SalTableColumn();
				this.colJahr1 = new PPJ.Runtime.Windows.SalTableColumn();
				this.colJahr2 = new PPJ.Runtime.Windows.SalTableColumn();
				this.colJahr3 = new PPJ.Runtime.Windows.SalTableColumn();
				this.SuspendLayout();
				// 
				// colBez
				// 
				this.colBez.Name = "colBez";
				// 
				// colJahr1
				// 
				this.colJahr1.Name = "colJahr1";
				// 
				// colJahr2
				// 
				this.colJahr2.Name = "colJahr2";
				// 
				// colJahr3
				// 
				this.colJahr3.Name = "colJahr3";
				// 
				// tblJS
				// 
				this.Controls.Add(this.colBez);
				this.Controls.Add(this.colJahr1);
				this.Controls.Add(this.colJahr2);
				this.Controls.Add(this.colJahr3);
				this.Name = "tblJS";
				this.ResumeLayout(false);
			}
			#endregion
		}
		#endregion
	}
}
