// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	/// <summary>
	/// </summary>
	public partial class frmKontierungen : SalFormWindow
	{
		#region Window Variables
		public SalSqlHandle hSqlUser = SalSqlHandle.Null;
		public SalNumber nFetchUser = 0;
		public SalString strSelect = "";
		public SalNumber nColor = 0;
		public SalNumber nRow = 0;
		public SalString lsDummy = "";
		public SalString strSKR = "";
		#endregion
		
		#region Constructors/Destructors
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public frmKontierungen()
		{
			// Assign global reference.
			App.frmKontierungen = this;
			// This call is required by the Windows Form Designer.
			InitializeComponent();
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Shows the form window.
		/// </summary>
		/// <param name="owner"></param>
		/// <returns></returns>
		public static frmKontierungen CreateWindow(Control owner)
		{
			frmKontierungen frm = new frmKontierungen();
			frm.Show(owner);
			return frm;
		}
		
		/// <summary>
		/// Returns the object instance associated with the window handle.
		/// </summary>
		/// <param name="handle"></param>
		/// <returns></returns>
		[DebuggerStepThrough]
		public static frmKontierungen FromHandle(SalWindowHandle handle)
		{
			return ((frmKontierungen)SalWindow.FromHandle(handle, typeof(frmKontierungen)));
		}
		#endregion
		
		#region Methods
		
		/// <summary>
		/// </summary>
		/// <returns></returns>
		public SalNumber PalNewRow()
		{
			#region Actions
			using (new SalContext(this))
			{
				if (PalSave()) 
				{
				}
				PalHoleTabelle();
				nRow = tblKonti.InsertRow(Sys.TBL_MaxRow);
				tblKonti.colBilanzierer.Number = 0;
				tblKonti.colSKR.Text = "SKR03";
				tblKonti.SetFocusCell(nRow, tblKonti.colCode, 0, -1);
			}

			return 0;
			#endregion
		}
		
		/// <summary>
		/// </summary>
		/// <returns></returns>
		public SalNumber PalSave()
		{
			#region Actions
			using (new SalContext(this))
			{
				Sal.WaitCursor(true);
				tblKonti.KillCellEdit();
				if (tblKonti.AnyRows((Sys.ROW_New | Sys.ROW_Edited), 0)) 
				{
					nRow = Sys.TBL_MinRow;
					while (true)
					{
						if (!(tblKonti.FindNextRow(ref nRow, (Sys.ROW_New | Sys.ROW_Edited), 0))) 
						{
							break;
						}
						tblKonti.SetFocusRow(nRow);
						if (tblKonti.colBilanzierer.Number == Sys.NUMBER_Null) 
						{
							tblKonti.colBilanzierer.Number = 0;
						}


						if (tblKonti.colCode.Text == "") 
						{
							Sal.MessageBox("Der Code darf nicht leer sein.", "Fehler", (Sys.MB_Ok | Sys.MB_IconStop));
						}
						else if (tblKonti.colSKR.Text == "") 
						{
							Sal.MessageBox("Der Kontenrahmen darf nicht leer sein.", "Fehler", (Sys.MB_Ok | Sys.MB_IconStop));
						}
						else
						{
							Int.SqlIstDa("FROM ko WHERE kocode = :frmKontierungen.tblKonti.colCode AND kobilanzierer = :frmKontierungen.tblKonti.colBilanzierer AND kokontenrahmen = :frmKontierungen.tblKonti.colSKR", ref Var.bExists);
							if (Var.bExists) 
							{
								Int.SqlImmed(@"UPDATE ko SET
kosoll = :frmKontierungen.tblKonti.colSoll,
kohaben = :frmKontierungen.tblKonti.colHaben
WHERE kocode = :frmKontierungen.tblKonti.colCode AND kobilanzierer = :frmKontierungen.tblKonti.colBilanzierer AND kokontenrahmen = :frmKontierungen.tblKonti.colSKR");
							}
							else
							{
								Int.SqlImmed(@"INSERT INTO ko
(kocode, kobilanzierer, kokontenrahmen, kosoll, kohaben)
VALUES( :frmKontierungen.tblKonti.colCode, :frmKontierungen.tblKonti.colBilanzierer, :frmKontierungen.tblKonti.colSKR, :frmKontierungen.tblKonti.colSoll, :frmKontierungen.tblKonti.colHaben)");
							}
							tblKonti.SetRowFlags(nRow, (Sys.ROW_New | Sys.ROW_Edited), false);
						}
					}
				}
				Sal.WaitCursor(false);
			}

			return 0;
			#endregion
		}
		
		/// <summary>
		/// </summary>
		/// <returns></returns>
		public SalNumber PalHoleTabelle()
		{
			#region Local Variables
			SqlLocals.PalHoleTabelleLocals locals = new SqlLocals.PalHoleTabelleLocals();
			#endregion
			
			#region Actions
			using (new SalContext(this, locals))
			{
				Int.SqlConnection(ref hSqlUser);
				strSelect = @"SELECT kocode, kobilanzierer, kokontenrahmen, kosoll, kohaben
INTO :frmKontierungen.tblKonti.colCode, :frmKontierungen.tblKonti.colBilanzierer, :frmKontierungen.tblKonti.colSKR, :frmKontierungen.tblKonti.colSoll, :frmKontierungen.tblKonti.colHaben
FROM ko ORDER BY kocode, kokontenrahmen, kobilanzierer";
				if (tblKonti.Populate(hSqlUser, strSelect, Sys.TBL_FillAll)) 
				{
					hSqlUser.Commit();
				}
				hSqlUser.Disconnect();

				return 0;
			}
			#endregion
		}
		#endregion
		
		#region Window Actions
		
		/// <summary>
		/// frmKontierungen WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void frmKontierungen_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Create:
					this.frmKontierungen_OnSAM_Create(sender, e);
					break;
				
				case Sys.SAM_Close:
					this.frmKontierungen_OnSAM_Close(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void frmKontierungen_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			Sal.WaitCursor(true);
			// Call SqlConnection(hSqlUser)
			this.PalHoleTabelle();

			// Call SalContextMenuSetPopup( tblKonti, 'frmKontierungenRightClick', 0)

			Sal.WaitCursor(false);
			#endregion
		}
		
		/// <summary>
		/// SAM_Close event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void frmKontierungen_OnSAM_Close(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// Call SqlDisconnect(hSqlUser)
			this.PalSave();
			#endregion
		}
		
		/// <summary>
		/// tblKonti WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void tblKonti_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Create:
					this.tblKonti_OnSAM_Create(sender, e);
					break;
				
				case Const.WM_KEYUP:
					this.tblKonti_OnWM_KEYUP(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void tblKonti_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			Int.SqlConnection(ref this.hSqlUser);
			this.tblKonti.colSKR.ClearList();
			this.hSqlUser.PrepareAndExecute("SELECT dscode INTO :frmKontierungen.strSKR FROM ds ORDER BY dscode");
			this.nFetchUser = this.hSqlUser.FetchNext();
			while (this.nFetchUser != Sys.FETCH_EOF) 
			{
				this.tblKonti.colSKR.AddListItem(this.strSKR);
				this.nFetchUser = this.hSqlUser.FetchNext();
			}
			this.hSqlUser.Commit();
			this.hSqlUser.Disconnect();
			#endregion
		}
		
		/// <summary>
		/// WM_KEYUP event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void tblKonti_OnWM_KEYUP(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			if (Sys.wParam == 45)  // Einf.
			{
				this.PalNewRow();
			}
			#endregion
		}
		
		/// <summary>
		/// pbNeu WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbNeu_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbNeu_OnSAM_Click(sender, e);
					break;
				
				case Const.WM_KEYUP:
					this.pbNeu_OnWM_KEYUP(sender, e);
					break;
				
				case Sys.SAM_Create:
					this.pbNeu_OnSAM_Create(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbNeu_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			this.PalNewRow();
			#endregion
		}
		
		/// <summary>
		/// WM_KEYUP event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbNeu_OnWM_KEYUP(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			if (Sys.wParam == 45)  // Einf.
			{
				this.PalNewRow();
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbNeu_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			e.Return = Int.XSalTooltipSetTextActive(this.pbNeu, "Neue Zeile hinzufügen.");
			return;
			#endregion
		}
		
		/// <summary>
		/// pbLoe WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbLoe_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbLoe_OnSAM_Click(sender, e);
					break;
				
				case Sys.SAM_Create:
					this.pbLoe_OnSAM_Create(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbLoe_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			if (this.tblKonti.AnyRows((Sys.ROW_Selected | Sys.ROW_MarkDeleted), 0)) 
			{
				this.nRow = Sys.TBL_MinRow;
				while (true)
				{
					if (!(this.tblKonti.FindNextRow(ref this.nRow, (Sys.ROW_Selected | Sys.ROW_MarkDeleted), 0))) 
					{
						break;
					}
					this.tblKonti.SetFocusRow(this.nRow);
					Int.SqlImmed("DELETE FROM ko WHERE kocode = :frmKontierungen.tblKonti.colCode AND kobilanzierer = :frmKontierungen.tblKonti.colBilanzierer AND kokontenrahmen = :frmKontierungen.tblKonti.colSKR");
					this.tblKonti.DeleteRow(this.nRow, Sys.TBL_NoAdjust);
				}
				this.PalSave();
				this.tblKonti.ResetTable();
				// If SalTblPopulate( tblBEZS,hSqlUser,strSelect,TBL_FillAll )
				this.PalHoleTabelle();
			}
			else
			{
				Sal.MessageBox(@"Vorher müssen die zu löschenden
Zeilen markiert werden !", "Markieren !", Sys.MB_IconAsterisk);
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbLoe_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			e.Return = Int.XSalTooltipSetTextActive(this.pbLoe, "Schwarz markierte Zeilen löschen.");
			return;
			#endregion
		}
		
		/// <summary>
		/// pbAbbruch WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbAbbruch_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbAbbruch_OnSAM_Click(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbAbbruch_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// Call SalDestroyWindow (hWndForm)
			this.PostMessage(Sys.SAM_Close, 0, 0);
			#endregion
		}
		#endregion
		
		#region tblKonti
		
		/// <summary>
		/// Child Table Window implementation.
		/// </summary>
		public partial class tblKontiTableWindow : SalTableWindow
		{
			// reference to the container form.
			private frmKontierungen _frmKontierungen = null;
			
			
			#region Constructors/Destructors
			
			/// <summary>
			/// Default Constructor.
			/// </summary>
			public tblKontiTableWindow()
			{
				// This call is required by the Windows Form Designer.
				InitializeComponent();
			}
			#endregion
			
			#region System Methods/Properties
			
			/// <summary>
			/// Parent form.
			/// </summary>
			private frmKontierungen frmKontierungen
			{
				[DebuggerStepThrough]
				get
				{
					if (_frmKontierungen == null) 
					{
						_frmKontierungen = (frmKontierungen)this.FindForm();
					}
					return _frmKontierungen;
				}
			}
			
			/// <summary>
			/// Returns the object instance associated with the window handle.
			/// </summary>
			/// <param name="handle"></param>
			/// <returns></returns>
			[DebuggerStepThrough]
			public static tblKontiTableWindow FromHandle(SalWindowHandle handle)
			{
				return ((tblKontiTableWindow)SalWindow.FromHandle(handle, typeof(tblKontiTableWindow)));
			}
			#endregion
		}
		#endregion
		
		#region SqlLocals
		
		/// <summary>
		/// Container class used to group the inner classes that contain
		/// the local variables that have been extracted from methods that use sql calls.
		/// </summary>
		private class SqlLocals
		{
			
			/// <summary>
			/// Contains the local variables that have been extracted from the
			/// method that uses sql calls and might need to access local bind variables.
			/// </summary>
			public class PalHoleTabelleLocals
			{
				public SalString strSelect1 = "";
			}
		}
		#endregion
	}
}
