// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	/// <summary>
	/// </summary>
	public partial class frmRechNachdruck : SalFormWindow
	{
		#region Window Variables
		public SalString strLLQuery = "";
		public SalDateTime dtMaxDat = SalDateTime.Null;
		#endregion
		
		#region Constructors/Destructors
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public frmRechNachdruck()
		{
			// Assign global reference.
			App.frmRechNachdruck = this;
			// This call is required by the Windows Form Designer.
			InitializeComponent();
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Shows the form window.
		/// </summary>
		/// <param name="owner"></param>
		/// <returns></returns>
		public static frmRechNachdruck CreateWindow(Control owner)
		{
			frmRechNachdruck frm = new frmRechNachdruck();
			frm.Show(owner);
			return frm;
		}
		
		/// <summary>
		/// Returns the object instance associated with the window handle.
		/// </summary>
		/// <param name="handle"></param>
		/// <returns></returns>
		[DebuggerStepThrough]
		public static frmRechNachdruck FromHandle(SalWindowHandle handle)
		{
			return ((frmRechNachdruck)SalWindow.FromHandle(handle, typeof(frmRechNachdruck)));
		}
		#endregion
		
		#region Window Actions
		
		/// <summary>
		/// frmRechNachdruck WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void frmRechNachdruck_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Create:
					this.frmRechNachdruck_OnSAM_Create(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Create event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void frmRechNachdruck_OnSAM_Create(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			this.dfHaltervon.Number = 1;
			this.dfHalterbis.Number = 999999;
			this.dfRechvon.Number = 1;
			this.dfRechbis.Number = 999999;
			this.dfRechDatvon.DateTime = new SalDateTime(1900, 1, 1);
			this.dfRechDatbis.DateTime = new SalDateTime(2099, 12, 31);
			// 21.11.16 Ä1445
			this.cbUeberw.Checked = false;
			#endregion
		}
		
		/// <summary>
		/// pbDrucken WindowActions Handler
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbDrucken_WindowActions(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			switch (e.ActionType)
			{
				case Sys.SAM_Click:
					this.pbDrucken_OnSAM_Click(sender, e);
					break;
			}
			#endregion
		}
		
		/// <summary>
		/// SAM_Click event handler.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		private void pbDrucken_OnSAM_Click(object sender, WindowActionsEventArgs e)
		{
			#region Actions
			e.Handled = true;
			// Call SalDisableWindow(pbDrucken)
			// 28.11.23
			if (this.dfHaltervon.Number == Sys.NUMBER_Null) 
			{
				this.dfHaltervon.Number = 1;
			}
			if (this.dfHalterbis.Number == Sys.NUMBER_Null) 
			{
				this.dfHalterbis.Number = 99999;
			}
			// 28.01.09 OTÄ161 Halterauswahl hinzugefügt
			// 17.07.12 Ä792
			this.strLLQuery = "(";
			if (this.dfArzt.Number != 0 && this.dfArzt.Number != Sys.NUMBER_Null) 
			{
				this.strLLQuery = this.strLLQuery + "rkarztnr = " + this.dfArzt.Number.ToString(0) + " AND ";
			}
			this.strLLQuery = this.strLLQuery + "rkhalternr BETWEEN " + this.dfHaltervon.Number.ToString(0) + " AND " + this.dfHalterbis.Number.ToString(0) + "  AND rkrechnr BETWEEN " + this.dfRechvon.Number.ToString(0) + " AND " + this.dfRechbis.Number.ToString(
				0) + " AND rkrechdat BETWEEN " + Int.PalDateToStr(this.dfRechDatvon.DateTime) + " AND " + Int.PalDateToStr(this.dfRechDatbis.DateTime);
			// 07.07.10 OTÄ439
			if (this.cbnurOP.Checked) 
			{
				this.strLLQuery = this.strLLQuery + " AND rkkzzahl<2 ";
			}

			this.strLLQuery = this.strLLQuery + " ) ";
			// 25.06.10 OTÄ134
			// 14.12.10 OTÄ508 TRUE -> cbZweit
			App.frmMain.bRepKopie = this.cbZweit.Checked;
			// 09.05.17 Ä1544
			Int.SqlImmedSel("SELECT MAX( rkrechdat) INTO :frmRechNachdruck.dtMaxDat FROM rk WHERE " + this.strLLQuery);
			if (this.dtMaxDat <= new SalDateTime(2017, 4, 24)) 
			{
				Var.strDummy1 = "Rechnung A4 tvn.lst";
			}
			else
			{
				Var.strDummy1 = "Rechnung A4.lst";
			}
			// 14.06.07 LL-Druck
			// LL
			if (1 == dlgLlDruck.ModalDialog(App.frmMain, Var.strDummy1, "RN")) 
			{
				if (this.cbUeberw.Checked) 
				{
					dlgLlDruck.ModalDialog(App.frmMain, "Überweisung A4.lst", "RN");
				}
			}
			#endregion
		}
		#endregion
	}
}
