// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class frmTagebuch
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
				
		/// <summary>
		/// Window Main Menu control.
		/// </summary>
		private SalFormMainMenu MainMenu;
		#endregion
		
		
		#region Window Controls
		private SalPopupMenu popupMenu__Bearbeiten;
		private SalMenuItem menuItem__Copy;
		private SalMenuItem menuItem_Clear;
		public SalPushbutton pbAbbruch;
		protected SalBackgroundText bkgd4;
		public SalDataField dfArztNr;
		protected SalBackgroundText bkgd5;
		public SalDataField dfHalterNr;
		protected SalBackgroundText bkgd6;
		public frmTagebuch.tblTagebuchTableWindow tblTagebuch;
		public SalPushbutton pbOk;
		public SalPushbutton pbDrucken;
		// Pushbutton: pbKreuztab
		// Message Actions
		// On SAM_Click
		// Set nErr = 1
		// Set strReportName = 'AKKREUZ'
		// Set hWndReport = SalReportTableView(tblTagebuch,hWndNULL,'AKKREUZ.QRP',nErr)
		public SalCheckBox cbohneHalter;
		public SalPushbutton pbStorno;
		public SalPushbutton pbSummen;
		public SalDataField dfSuAnzahl;
		public SalDataField dfSuProz;
		public SalDataField dfSuDM;
		public SalDataField dfSuRechSumm;
		public SalCheckBox cbRG;
		public SalCheckBox cbMG;
		public SalCheckBox cbMB;
		public SalCheckBox cbBR;
		public SalListBox lbPrinters;
		public VisCalendarDropDown dfDatum;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.MainMenu = new PPJ.Runtime.Windows.SalFormMainMenu();
            this.popupMenu__Bearbeiten = new PPJ.Runtime.Windows.SalPopupMenu();
            this.menuItem__Copy = new PPJ.Runtime.Windows.SalMenuItem();
            this.menuItem_Clear = new PPJ.Runtime.Windows.SalMenuItem();
            this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
            this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
            this.dfDatum = new PPJ.Runtime.Vis.VisCalendarDropDown();
            this.lbPrinters = new PPJ.Runtime.Windows.SalListBox();
            this.cbBR = new PPJ.Runtime.Windows.SalCheckBox();
            this.cbMB = new PPJ.Runtime.Windows.SalCheckBox();
            this.cbMG = new PPJ.Runtime.Windows.SalCheckBox();
            this.cbRG = new PPJ.Runtime.Windows.SalCheckBox();
            this.dfSuRechSumm = new PPJ.Runtime.Windows.SalDataField();
            this.dfSuDM = new PPJ.Runtime.Windows.SalDataField();
            this.dfSuProz = new PPJ.Runtime.Windows.SalDataField();
            this.dfSuAnzahl = new PPJ.Runtime.Windows.SalDataField();
            this.pbSummen = new PPJ.Runtime.Windows.SalPushbutton();
            this.pbStorno = new PPJ.Runtime.Windows.SalPushbutton();
            this.cbohneHalter = new PPJ.Runtime.Windows.SalCheckBox();
            this.pbDrucken = new PPJ.Runtime.Windows.SalPushbutton();
            this.pbOk = new PPJ.Runtime.Windows.SalPushbutton();
            this.tblTagebuch = ((Moveta.Intern.frmTagebuch.tblTagebuchTableWindow)(CreateTableWindow(typeof(Moveta.Intern.frmTagebuch.tblTagebuchTableWindow))));
            this.dfHalterNr = new PPJ.Runtime.Windows.SalDataField();
            this.dfArztNr = new PPJ.Runtime.Windows.SalDataField();
            this.bkgd6 = new PPJ.Runtime.Windows.SalBackgroundText();
            this.bkgd5 = new PPJ.Runtime.Windows.SalBackgroundText();
            this.bkgd4 = new PPJ.Runtime.Windows.SalBackgroundText();
            this.ClientArea.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.RibbonBar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.StatusBar)).BeginInit();
            this.ToolBar.SuspendLayout();
            this.tblTagebuch.SuspendLayout();
            this.SuspendLayout();
            // 
            // ClientArea
            // 
            this.ClientArea.Controls.Add(this.dfDatum);
            this.ClientArea.Controls.Add(this.lbPrinters);
            this.ClientArea.Controls.Add(this.cbBR);
            this.ClientArea.Controls.Add(this.cbMB);
            this.ClientArea.Controls.Add(this.cbMG);
            this.ClientArea.Controls.Add(this.cbRG);
            this.ClientArea.Controls.Add(this.dfSuRechSumm);
            this.ClientArea.Controls.Add(this.dfSuDM);
            this.ClientArea.Controls.Add(this.dfSuProz);
            this.ClientArea.Controls.Add(this.dfSuAnzahl);
            this.ClientArea.Controls.Add(this.pbSummen);
            this.ClientArea.Controls.Add(this.pbStorno);
            this.ClientArea.Controls.Add(this.cbohneHalter);
            this.ClientArea.Controls.Add(this.pbDrucken);
            this.ClientArea.Controls.Add(this.pbOk);
            this.ClientArea.Controls.Add(this.tblTagebuch);
            this.ClientArea.Controls.Add(this.dfHalterNr);
            this.ClientArea.Controls.Add(this.dfArztNr);
            this.ClientArea.Controls.Add(this.bkgd6);
            this.ClientArea.Controls.Add(this.bkgd5);
            this.ClientArea.Controls.Add(this.bkgd4);
            this.ClientArea.Location = new System.Drawing.Point(0, 60);
            this.ClientArea.Size = new System.Drawing.Size(760, 563);
            this.ClientArea.TabIndex = 0;
            // 
            // RibbonBar
            // 
            this.RibbonBar.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.RibbonBar.Location = new System.Drawing.Point(0, 60);
            this.RibbonBar.Size = new System.Drawing.Size(760, 152);
            // 
            // StatusBar
            // 
            this.StatusBar.Location = new System.Drawing.Point(0, 623);
            this.StatusBar.Size = new System.Drawing.Size(760, 23);
            // 
            // MainMenu
            // 
            this.MainMenu.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
            this.popupMenu__Bearbeiten});
            // 
            // popupMenu__Bearbeiten
            // 
            this.popupMenu__Bearbeiten.Index = 0;
            this.popupMenu__Bearbeiten.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
            this.menuItem__Copy,
            this.menuItem_Clear});
            this.popupMenu__Bearbeiten.StatusText = "Stammdaten";
            this.popupMenu__Bearbeiten.Text = "&Bearbeiten";
            // 
            // menuItem__Copy
            // 
            this.menuItem__Copy.Index = 0;
            this.menuItem__Copy.Shortcut = System.Windows.Forms.Shortcut.CtrlIns;
            this.menuItem__Copy.StatusText = "Copies the selection and puts it on the clipboard";
            this.menuItem__Copy.Text = "&Copy";
            this.menuItem__Copy.MenuActions += new PPJ.Runtime.Windows.SalMenuActionsHandler(this.menuItem__Copy_MenuActions);
            this.menuItem__Copy.EnabledWhen += new PPJ.Runtime.Windows.SalMenuEnabledWhenHandler(this.menuItem__Copy_EnabledWhen);
            // 
            // menuItem_Clear
            // 
            this.menuItem_Clear.Index = 1;
            this.menuItem_Clear.Shortcut = System.Windows.Forms.Shortcut.Del;
            this.menuItem_Clear.StatusText = "Clears the selection";
            this.menuItem_Clear.Text = "C&lear";
            this.menuItem_Clear.MenuActions += new PPJ.Runtime.Windows.SalMenuActionsHandler(this.menuItem_Clear_MenuActions);
            this.menuItem_Clear.EnabledWhen += new PPJ.Runtime.Windows.SalMenuEnabledWhenHandler(this.menuItem_Clear_EnabledWhen);
            // 
            // ToolBar
            // 
            this.ToolBar.BackColor = System.Drawing.SystemColors.Control;
            this.ToolBar.Controls.Add(this.pbAbbruch);
            this.ToolBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.ToolBar.Font = new System.Drawing.Font("Tahoma", 8F);
            this.ToolBar.Location = new System.Drawing.Point(0, 0);
            this.ToolBar.Name = "ToolBar";
            this.ToolBar.Size = new System.Drawing.Size(760, 60);
            this.ToolBar.TabIndex = 1;
            this.ToolBar.TabStop = true;
            this.ToolBar.Visible = false;
            // 
            // pbAbbruch
            // 
            this.pbAbbruch.AcceleratorKey = System.Windows.Forms.Keys.Escape;
            this.pbAbbruch.BackColor = System.Drawing.SystemColors.Control;
            this.pbAbbruch.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold);
            this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
            this.pbAbbruch.Name = "pbAbbruch";
            this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
            this.pbAbbruch.TabIndex = 0;
            this.pbAbbruch.Text = "Abbruch";
            this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.pbAbbruch.TransparentColor = System.Drawing.Color.Empty;
            this.pbAbbruch.UseVisualStyleBackColor = true;
            this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
            // 
            // dfDatum
            // 
            this.dfDatum.CalendarForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(32)))), ((int)(((byte)(32)))), ((int)(((byte)(32)))));
            this.dfDatum.CalendarMonthBackground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.dfDatum.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(233)))), ((int)(((byte)(235)))));
            this.dfDatum.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(48)))), ((int)(((byte)(48)))));
            this.dfDatum.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.dfDatum.Format = null;
            this.dfDatum.Location = new System.Drawing.Point(101, 49);
            this.dfDatum.Name = "dfDatum";
            this.dfDatum.Size = new System.Drawing.Size(116, 22);
            this.dfDatum.TabIndex = 20;
            this.dfDatum.Text = "1/29/2024";
            this.dfDatum.Value = new PPJ.Runtime.SalDateTime(2024, 1, 29, 8, 25, 43, 205);
            this.dfDatum.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.dfDatum_WindowActions);
            // 
            // lbPrinters
            // 
            this.lbPrinters.BackColor = System.Drawing.Color.White;
            this.lbPrinters.Font = new System.Drawing.Font("Tahoma", 8F);
            this.lbPrinters.Location = new System.Drawing.Point(525, 7);
            this.lbPrinters.Name = "lbPrinters";
            this.lbPrinters.Size = new System.Drawing.Size(204, 56);
            this.lbPrinters.TabIndex = 19;
            this.lbPrinters.UseCustomTabOffsets = true;
            // 
            // cbBR
            // 
            this.cbBR.Font = new System.Drawing.Font("Tahoma", 8F);
            this.cbBR.Location = new System.Drawing.Point(293, 7);
            this.cbBR.Name = "cbBR";
            this.cbBR.Size = new System.Drawing.Size(36, 19);
            this.cbBR.TabIndex = 18;
            this.cbBR.Text = "BR";
            this.cbBR.UseVisualStyleBackColor = true;
            // 
            // cbMB
            // 
            this.cbMB.Font = new System.Drawing.Font("Tahoma", 9F);
            this.cbMB.Location = new System.Drawing.Point(257, 7);
            this.cbMB.Name = "cbMB";
            this.cbMB.Size = new System.Drawing.Size(36, 19);
            this.cbMB.TabIndex = 17;
            this.cbMB.Text = "MB";
            this.cbMB.UseVisualStyleBackColor = true;
            // 
            // cbMG
            // 
            this.cbMG.Font = new System.Drawing.Font("Tahoma", 9F);
            this.cbMG.Location = new System.Drawing.Point(215, 7);
            this.cbMG.Name = "cbMG";
            this.cbMG.Size = new System.Drawing.Size(42, 19);
            this.cbMG.TabIndex = 16;
            this.cbMG.Text = "MG";
            this.cbMG.UseVisualStyleBackColor = true;
            // 
            // cbRG
            // 
            this.cbRG.Font = new System.Drawing.Font("Tahoma", 9F);
            this.cbRG.Location = new System.Drawing.Point(173, 7);
            this.cbRG.Name = "cbRG";
            this.cbRG.Size = new System.Drawing.Size(42, 19);
            this.cbRG.TabIndex = 15;
            this.cbRG.Text = "RG";
            this.cbRG.UseVisualStyleBackColor = true;
            // 
            // dfSuRechSumm
            // 
            this.dfSuRechSumm.BackColor = System.Drawing.SystemColors.Window;
            this.dfSuRechSumm.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfSuRechSumm.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfSuRechSumm.Font = new System.Drawing.Font("Tahoma", 8F);
            this.dfSuRechSumm.Format = "#,##0.00";
            this.dfSuRechSumm.Location = new System.Drawing.Point(434, 390);
            this.dfSuRechSumm.MaxLength = 100;
            this.dfSuRechSumm.Name = "dfSuRechSumm";
            this.dfSuRechSumm.ReadOnly = true;
            this.dfSuRechSumm.Size = new System.Drawing.Size(66, 17);
            this.dfSuRechSumm.TabIndex = 14;
            // 
            // dfSuDM
            // 
            this.dfSuDM.BackColor = System.Drawing.SystemColors.Window;
            this.dfSuDM.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfSuDM.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfSuDM.Font = new System.Drawing.Font("Tahoma", 8F);
            this.dfSuDM.Format = "#,##0.00";
            this.dfSuDM.Location = new System.Drawing.Point(368, 390);
            this.dfSuDM.MaxLength = 100;
            this.dfSuDM.Name = "dfSuDM";
            this.dfSuDM.ReadOnly = true;
            this.dfSuDM.Size = new System.Drawing.Size(54, 17);
            this.dfSuDM.TabIndex = 13;
            // 
            // dfSuProz
            // 
            this.dfSuProz.BackColor = System.Drawing.SystemColors.Window;
            this.dfSuProz.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfSuProz.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfSuProz.Font = new System.Drawing.Font("Tahoma", 8F);
            this.dfSuProz.Format = "#,##0.00";
            this.dfSuProz.Location = new System.Drawing.Point(329, 390);
            this.dfSuProz.MaxLength = 100;
            this.dfSuProz.Name = "dfSuProz";
            this.dfSuProz.ReadOnly = true;
            this.dfSuProz.Size = new System.Drawing.Size(33, 17);
            this.dfSuProz.TabIndex = 12;
            // 
            // dfSuAnzahl
            // 
            this.dfSuAnzahl.BackColor = System.Drawing.SystemColors.Window;
            this.dfSuAnzahl.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfSuAnzahl.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfSuAnzahl.Font = new System.Drawing.Font("Tahoma", 8F);
            this.dfSuAnzahl.Format = "#0";
            this.dfSuAnzahl.Location = new System.Drawing.Point(296, 390);
            this.dfSuAnzahl.MaxLength = 100;
            this.dfSuAnzahl.Name = "dfSuAnzahl";
            this.dfSuAnzahl.ReadOnly = true;
            this.dfSuAnzahl.Size = new System.Drawing.Size(33, 17);
            this.dfSuAnzahl.TabIndex = 11;
            // 
            // pbSummen
            // 
            this.pbSummen.AcceleratorKey = System.Windows.Forms.Keys.None;
            this.pbSummen.BackColor = System.Drawing.SystemColors.Control;
            this.pbSummen.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold);
            this.pbSummen.Location = new System.Drawing.Point(17, 387);
            this.pbSummen.Name = "pbSummen";
            this.pbSummen.Size = new System.Drawing.Size(270, 20);
            this.pbSummen.TabIndex = 10;
            this.pbSummen.Text = "&Summen für markierte Zeilen bilden :";
            this.pbSummen.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.pbSummen.TransparentColor = System.Drawing.Color.Empty;
            this.pbSummen.UseVisualStyleBackColor = true;
            this.pbSummen.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbSummen_WindowActions);
            // 
            // pbStorno
            // 
            this.pbStorno.AcceleratorKey = System.Windows.Forms.Keys.None;
            this.pbStorno.BackColor = System.Drawing.SystemColors.Control;
            this.pbStorno.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold);
            this.pbStorno.Location = new System.Drawing.Point(17, 363);
            this.pbStorno.Name = "pbStorno";
            this.pbStorno.Size = new System.Drawing.Size(270, 20);
            this.pbStorno.TabIndex = 9;
            this.pbStorno.Text = "markierte Zeile s&tornieren";
            this.pbStorno.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.pbStorno.TransparentColor = System.Drawing.Color.Empty;
            this.pbStorno.UseVisualStyleBackColor = true;
            this.pbStorno.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbStorno_WindowActions);
            // 
            // cbohneHalter
            // 
            this.cbohneHalter.Font = new System.Drawing.Font("Tahoma", 9F);
            this.cbohneHalter.Location = new System.Drawing.Point(173, 31);
            this.cbohneHalter.Name = "cbohneHalter";
            this.cbohneHalter.Size = new System.Drawing.Size(156, 19);
            this.cbohneHalter.TabIndex = 8;
            this.cbohneHalter.Text = "ohne Halter-Daten";
            this.cbohneHalter.UseVisualStyleBackColor = true;
            // 
            // pbDrucken
            // 
            this.pbDrucken.AcceleratorKey = System.Windows.Forms.Keys.None;
            this.pbDrucken.BackColor = System.Drawing.SystemColors.Control;
            this.pbDrucken.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold);
            this.pbDrucken.Image = global::Moveta.Intern.Properties.Resources.printer;
            this.pbDrucken.Location = new System.Drawing.Point(446, 7);
            this.pbDrucken.Name = "pbDrucken";
            this.pbDrucken.Size = new System.Drawing.Size(69, 56);
            this.pbDrucken.TabIndex = 7;
            this.pbDrucken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.pbDrucken.TransparentColor = System.Drawing.Color.White;
            this.pbDrucken.UseVisualStyleBackColor = true;
            this.pbDrucken.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbDrucken_WindowActions);
            // 
            // pbOk
            // 
            this.pbOk.AcceleratorKey = System.Windows.Forms.Keys.F12;
            this.pbOk.BackColor = System.Drawing.SystemColors.Control;
            this.pbOk.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold);
            this.pbOk.Image = global::Moveta.Intern.Properties.Resources.ok;
            this.pbOk.Location = new System.Drawing.Point(365, 7);
            this.pbOk.Name = "pbOk";
            this.pbOk.Size = new System.Drawing.Size(72, 56);
            this.pbOk.TabIndex = 6;
            this.pbOk.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.pbOk.TransparentColor = System.Drawing.Color.Empty;
            this.pbOk.UseVisualStyleBackColor = true;
            this.pbOk.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbOk_WindowActions);
            // 
            // tblTagebuch
            // 
            this.tblTagebuch.BackColor = System.Drawing.Color.White;
            this.tblTagebuch.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            // 
            // tblTagebuch.coldtDatum
            // 
            this.tblTagebuch.coldtDatum.DataType = PPJ.Runtime.Windows.DataType.DateTime;
            this.tblTagebuch.coldtDatum.Enabled = false;
            this.tblTagebuch.coldtDatum.Format = "G";
            this.tblTagebuch.coldtDatum.Name = "coldtDatum";
            this.tblTagebuch.coldtDatum.Position = 1;
            this.tblTagebuch.coldtDatum.Title = "Datum";
            this.tblTagebuch.coldtDatum.Width = 81;
            // 
            // tblTagebuch.colnAnzahl
            // 
            this.tblTagebuch.colnAnzahl.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnAnzahl.Enabled = false;
            this.tblTagebuch.colnAnzahl.Format = "#0";
            this.tblTagebuch.colnAnzahl.Name = "colnAnzahl";
            this.tblTagebuch.colnAnzahl.Position = 7;
            this.tblTagebuch.colnAnzahl.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnAnzahl.Title = "Anzahl";
            this.tblTagebuch.colnAnzahl.Width = 48;
            // 
            // tblTagebuch.colnArztNr
            // 
            this.tblTagebuch.colnArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnArztNr.Enabled = false;
            this.tblTagebuch.colnArztNr.Format = "#0";
            this.tblTagebuch.colnArztNr.MaxLength = 4;
            this.tblTagebuch.colnArztNr.Name = "colnArztNr";
            this.tblTagebuch.colnArztNr.Position = 2;
            this.tblTagebuch.colnArztNr.Title = "Arzt";
            this.tblTagebuch.colnArztNr.Width = 41;
            // 
            // tblTagebuch.colnDauer
            // 
            this.tblTagebuch.colnDauer.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnDauer.Enabled = false;
            this.tblTagebuch.colnDauer.Format = "#0";
            this.tblTagebuch.colnDauer.Name = "colnDauer";
            this.tblTagebuch.colnDauer.Position = 12;
            this.tblTagebuch.colnDauer.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnDauer.Title = "Tage";
            this.tblTagebuch.colnDauer.Width = 42;
            // 
            // tblTagebuch.colnDM
            // 
            this.tblTagebuch.colnDM.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnDM.Enabled = false;
            this.tblTagebuch.colnDM.Format = "#,##0.00";
            this.tblTagebuch.colnDM.Name = "colnDM";
            this.tblTagebuch.colnDM.Position = 9;
            this.tblTagebuch.colnDM.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnDM.Title = "€";
            this.tblTagebuch.colnDM.Width = 63;
            // 
            // tblTagebuch.colnHalterNr
            // 
            this.tblTagebuch.colnHalterNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnHalterNr.Enabled = false;
            this.tblTagebuch.colnHalterNr.Format = "#0";
            this.tblTagebuch.colnHalterNr.Name = "colnHalterNr";
            this.tblTagebuch.colnHalterNr.Position = 3;
            this.tblTagebuch.colnHalterNr.Title = "Halter";
            this.tblTagebuch.colnHalterNr.Width = 57;
            // 
            // tblTagebuch.colnProzGeb
            // 
            this.tblTagebuch.colnProzGeb.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnProzGeb.Enabled = false;
            this.tblTagebuch.colnProzGeb.Format = "#,##0.00";
            this.tblTagebuch.colnProzGeb.Name = "colnProzGeb";
            this.tblTagebuch.colnProzGeb.Position = 8;
            this.tblTagebuch.colnProzGeb.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnProzGeb.Title = "%";
            this.tblTagebuch.colnProzGeb.Width = 44;
            // 
            // tblTagebuch.colnProzNr
            // 
            this.tblTagebuch.colnProzNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnProzNr.Enabled = false;
            this.tblTagebuch.colnProzNr.Format = "#0";
            this.tblTagebuch.colnProzNr.Name = "colnProzNr";
            this.tblTagebuch.colnProzNr.Position = 11;
            this.tblTagebuch.colnProzNr.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnProzNr.Title = "PR";
            this.tblTagebuch.colnProzNr.Width = 36;
            // 
            // tblTagebuch.colnRechNr
            // 
            this.tblTagebuch.colnRechNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnRechNr.Enabled = false;
            this.tblTagebuch.colnRechNr.Format = "#0";
            this.tblTagebuch.colnRechNr.Name = "colnRechNr";
            this.tblTagebuch.colnRechNr.Position = 4;
            this.tblTagebuch.colnRechNr.Title = "Rech";
            this.tblTagebuch.colnRechNr.Width = 66;
            // 
            // tblTagebuch.colnRechSumme
            // 
            this.tblTagebuch.colnRechSumme.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.tblTagebuch.colnRechSumme.Enabled = false;
            this.tblTagebuch.colnRechSumme.Format = "#,##0.00";
            this.tblTagebuch.colnRechSumme.Name = "colnRechSumme";
            this.tblTagebuch.colnRechSumme.Position = 10;
            this.tblTagebuch.colnRechSumme.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.tblTagebuch.colnRechSumme.Title = "RechSumme";
            this.tblTagebuch.colnRechSumme.Width = 81;
            // 
            // tblTagebuch.colsTyp
            // 
            this.tblTagebuch.colsTyp.Enabled = false;
            this.tblTagebuch.colsTyp.MaxLength = 2;
            this.tblTagebuch.colsTyp.Name = "colsTyp";
            this.tblTagebuch.colsTyp.Position = 5;
            this.tblTagebuch.colsTyp.Title = "KZ";
            this.tblTagebuch.colsTyp.Width = 25;
            // 
            // tblTagebuch.colsTypDetail
            // 
            this.tblTagebuch.colsTypDetail.Enabled = false;
            this.tblTagebuch.colsTypDetail.MaxLength = 5;
            this.tblTagebuch.colsTypDetail.Name = "colsTypDetail";
            this.tblTagebuch.colsTypDetail.Position = 6;
            this.tblTagebuch.colsTypDetail.Title = "Detail";
            this.tblTagebuch.colsTypDetail.Width = 51;
            this.tblTagebuch.Font = new System.Drawing.Font("Tahoma", 9F);
            this.tblTagebuch.Location = new System.Drawing.Point(14, 75);
            this.tblTagebuch.Name = "tblTagebuch";
            this.tblTagebuch.Size = new System.Drawing.Size(717, 284);
            this.tblTagebuch.TabIndex = 5;
            this.tblTagebuch.UseVisualStyles = true;
            this.tblTagebuch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.tblTagebuch_WindowActions);
            // 
            // dfHalterNr
            // 
            this.dfHalterNr.BackColor = System.Drawing.Color.White;
            this.dfHalterNr.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfHalterNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfHalterNr.Font = new System.Drawing.Font("Tahoma", 9F);
            this.dfHalterNr.Format = "#0";
            this.dfHalterNr.Location = new System.Drawing.Point(101, 25);
            this.dfHalterNr.MaxLength = 5;
            this.dfHalterNr.Name = "dfHalterNr";
            this.dfHalterNr.Size = new System.Drawing.Size(48, 16);
            this.dfHalterNr.TabIndex = 3;
            // 
            // dfArztNr
            // 
            this.dfArztNr.BackColor = System.Drawing.Color.White;
            this.dfArztNr.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dfArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
            this.dfArztNr.Font = new System.Drawing.Font("Tahoma", 9F);
            this.dfArztNr.Format = "#0";
            this.dfArztNr.Location = new System.Drawing.Point(101, 10);
            this.dfArztNr.MaxLength = 4;
            this.dfArztNr.Name = "dfArztNr";
            this.dfArztNr.Size = new System.Drawing.Size(48, 16);
            this.dfArztNr.TabIndex = 1;
            this.dfArztNr.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.dfArztNr_WindowActions);
            // 
            // bkgd6
            // 
            this.bkgd6.Font = new System.Drawing.Font("Tahoma", 9F);
            this.bkgd6.Location = new System.Drawing.Point(17, 49);
            this.bkgd6.Name = "bkgd6";
            this.bkgd6.Size = new System.Drawing.Size(81, 20);
            this.bkgd6.TabIndex = 4;
            this.bkgd6.Text = "nur Datum";
            // 
            // bkgd5
            // 
            this.bkgd5.Font = new System.Drawing.Font("Tahoma", 9F);
            this.bkgd5.Location = new System.Drawing.Point(17, 25);
            this.bkgd5.Name = "bkgd5";
            this.bkgd5.Size = new System.Drawing.Size(60, 17);
            this.bkgd5.TabIndex = 2;
            this.bkgd5.Text = "Halter-Nr.";
            // 
            // bkgd4
            // 
            this.bkgd4.Font = new System.Drawing.Font("Tahoma", 9F);
            this.bkgd4.Location = new System.Drawing.Point(17, 10);
            this.bkgd4.Name = "bkgd4";
            this.bkgd4.Size = new System.Drawing.Size(50, 21);
            this.bkgd4.TabIndex = 0;
            this.bkgd4.Text = "Arzt-Nr.";
            // 
            // frmTagebuch
            // 
            this.ClientSize = new System.Drawing.Size(760, 646);
            this.Controls.Add(this.ToolBar);
            this.Location = new System.Drawing.Point(38, 10);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmTagebuch";
            this.RibbonMenu = this.MainMenu;
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Tagebuch";
            this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.frmTagebuch_WindowActions);
            this.Controls.SetChildIndex(this.StatusBar, 0);
            this.Controls.SetChildIndex(this.ToolBar, 0);
            this.Controls.SetChildIndex(this.ClientArea, 0);
            this.Controls.SetChildIndex(this.RibbonBar, 0);
            this.ClientArea.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.RibbonBar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.StatusBar)).EndInit();
            this.ToolBar.ResumeLayout(false);
            this.tblTagebuch.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.frmTagebuch == this) 
			{
				App.frmTagebuch = null;
			}
			base.Dispose(disposing);
		}
		#endregion
		
		#region tblTagebuch
		
		public partial class tblTagebuchTableWindow
		{
			#region Window Controls
			public SalTableColumn coldtDatum;
			public SalTableColumn colnArztNr;
			public SalTableColumn colnHalterNr;
			public SalTableColumn colnRechNr;
			public SalTableColumn colsTyp;
			public SalTableColumn colsTypDetail;
			public SalTableColumn colnAnzahl;
			public SalTableColumn colnProzGeb;
			public SalTableColumn colnDM;
			public SalTableColumn colnRechSumme;
			public SalTableColumn colnProzNr;
			public SalTableColumn colnDauer;
			#endregion
			
			#region Windows Form Designer generated code
			
			/// <summary>
			/// Required method for Designer support - do not modify
			/// the contents of this method with the code editor.
			/// </summary>
			private void InitializeComponent()
			{
				this.coldtDatum = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnArztNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnHalterNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnRechNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsTyp = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsTypDetail = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnAnzahl = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnProzGeb = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnDM = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnRechSumme = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnProzNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnDauer = new PPJ.Runtime.Windows.SalTableColumn();
				this.SuspendLayout();
				// 
				// coldtDatum
				// 
				this.coldtDatum.Name = "coldtDatum";
				// 
				// colnArztNr
				// 
				this.colnArztNr.Name = "colnArztNr";
				// 
				// colnHalterNr
				// 
				this.colnHalterNr.Name = "colnHalterNr";
				// 
				// colnRechNr
				// 
				this.colnRechNr.Name = "colnRechNr";
				// 
				// colsTyp
				// 
				this.colsTyp.Name = "colsTyp";
				// 
				// colsTypDetail
				// 
				this.colsTypDetail.Name = "colsTypDetail";
				// 
				// colnAnzahl
				// 
				this.colnAnzahl.Name = "colnAnzahl";
				// 
				// colnProzGeb
				// 
				this.colnProzGeb.Name = "colnProzGeb";
				// 
				// colnDM
				// 
				this.colnDM.Name = "colnDM";
				// 
				// colnRechSumme
				// 
				this.colnRechSumme.Name = "colnRechSumme";
				// 
				// colnProzNr
				// 
				this.colnProzNr.Name = "colnProzNr";
				// 
				// colnDauer
				// 
				this.colnDauer.Name = "colnDauer";
				// 
				// tblTagebuch
				// 
				this.Controls.Add(this.coldtDatum);
				this.Controls.Add(this.colnArztNr);
				this.Controls.Add(this.colnHalterNr);
				this.Controls.Add(this.colnRechNr);
				this.Controls.Add(this.colsTyp);
				this.Controls.Add(this.colsTypDetail);
				this.Controls.Add(this.colnAnzahl);
				this.Controls.Add(this.colnProzGeb);
				this.Controls.Add(this.colnDM);
				this.Controls.Add(this.colnRechSumme);
				this.Controls.Add(this.colnProzNr);
				this.Controls.Add(this.colnDauer);
				this.Name = "tblTagebuch";
				this.ResumeLayout(false);
			}
			#endregion
		}
		#endregion
	}
}
