// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class frmTSKBeihilfen
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// Client area panel.
		/// </summary>
		protected SalFormClientArea ClientArea;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		protected SalGroupBox grpAuswahl;
		public SalRadioButton rbunerl;
		public SalRadioButton rbunbekannt;
		public SalRadioButton rballe;
		public SalPushbutton pbAnzeigen;
		protected SalGroupBox grp2;
		public SalPushbutton pbDrucken;
		public SalPushbutton pbErinnerung;
		public SalListBox lbPrinters;
		public frmTSKBeihilfen.tblBeihilfenTableWindow tblBeihilfen;
		protected SalGroupBox grpSort;
		public SalRadioButton rbSortEinleseDatum;
		public SalRadioButton rbSortRegArzt;
		protected SalBackgroundText bkgd1;
		protected SalBackgroundText bkgd2;
		public SalDataField dfArztNr;
		public SalDataField dfHalterName;
		protected SalBackgroundText bkgd3;
		public SalDataField dfMonate;
		protected SalBackgroundText bkgd4;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.ClientArea = new PPJ.Runtime.Windows.SalFormClientArea();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.grpAuswahl = new PPJ.Runtime.Windows.SalGroupBox();
			this.rbunerl = new PPJ.Runtime.Windows.SalRadioButton();
			this.rbunbekannt = new PPJ.Runtime.Windows.SalRadioButton();
			this.rballe = new PPJ.Runtime.Windows.SalRadioButton();
			this.pbAnzeigen = new PPJ.Runtime.Windows.SalPushbutton();
			this.grp2 = new PPJ.Runtime.Windows.SalGroupBox();
			this.pbDrucken = new PPJ.Runtime.Windows.SalPushbutton();
			this.pbErinnerung = new PPJ.Runtime.Windows.SalPushbutton();
			this.lbPrinters = new PPJ.Runtime.Windows.SalListBox();
			this.tblBeihilfen = (frmTSKBeihilfen.tblBeihilfenTableWindow)CreateTableWindow(typeof(frmTSKBeihilfen.tblBeihilfenTableWindow));
			this.grpSort = new PPJ.Runtime.Windows.SalGroupBox();
			this.rbSortEinleseDatum = new PPJ.Runtime.Windows.SalRadioButton();
			this.rbSortRegArzt = new PPJ.Runtime.Windows.SalRadioButton();
			this.bkgd1 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.bkgd2 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfArztNr = new PPJ.Runtime.Windows.SalDataField();
			this.dfHalterName = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd3 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.dfMonate = new PPJ.Runtime.Windows.SalDataField();
			this.bkgd4 = new PPJ.Runtime.Windows.SalBackgroundText();
			this.ToolBar.SuspendLayout();
			this.ClientArea.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// ClientArea
			// 
			this.ClientArea.Name = "ClientArea";
			this.ClientArea.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.ClientArea.Controls.Add(this.dfMonate);
			this.ClientArea.Controls.Add(this.dfHalterName);
			this.ClientArea.Controls.Add(this.dfArztNr);
			this.ClientArea.Controls.Add(this.rbSortRegArzt);
			this.ClientArea.Controls.Add(this.rbSortEinleseDatum);
			this.ClientArea.Controls.Add(this.tblBeihilfen);
			this.ClientArea.Controls.Add(this.lbPrinters);
			this.ClientArea.Controls.Add(this.pbErinnerung);
			this.ClientArea.Controls.Add(this.pbDrucken);
			this.ClientArea.Controls.Add(this.pbAnzeigen);
			this.ClientArea.Controls.Add(this.rballe);
			this.ClientArea.Controls.Add(this.rbunbekannt);
			this.ClientArea.Controls.Add(this.rbunerl);
			this.ClientArea.Controls.Add(this.bkgd4);
			this.ClientArea.Controls.Add(this.bkgd3);
			this.ClientArea.Controls.Add(this.bkgd2);
			this.ClientArea.Controls.Add(this.bkgd1);
			this.ClientArea.Controls.Add(this.grpSort);
			this.ClientArea.Controls.Add(this.grp2);
			this.ClientArea.Controls.Add(this.grpAuswahl);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// grpAuswahl
			// 
			this.grpAuswahl.Name = "grpAuswahl";
			this.grpAuswahl.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.grpAuswahl.Text = "Auswahl";
			this.grpAuswahl.Location = new System.Drawing.Point(11, 7);
			this.grpAuswahl.Size = new System.Drawing.Size(198, 88);
			this.grpAuswahl.TabIndex = 0;
			// 
			// rbunerl
			// 
			this.rbunerl.Name = "rbunerl";
			this.rbunerl.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rbunerl.Text = "unerledigte TSK-Beihilfen";
			this.rbunerl.Location = new System.Drawing.Point(23, 23);
			this.rbunerl.Size = new System.Drawing.Size(180, 24);
			this.rbunerl.TabIndex = 1;
			// 
			// rbunbekannt
			// 
			this.rbunbekannt.Name = "rbunbekannt";
			this.rbunbekannt.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rbunbekannt.Text = "unbekannte Arzt-Reg.Nr.";
			this.rbunbekannt.Location = new System.Drawing.Point(23, 47);
			this.rbunbekannt.Size = new System.Drawing.Size(174, 24);
			this.rbunbekannt.TabIndex = 2;
			// 
			// rballe
			// 
			this.rballe.Name = "rballe";
			this.rballe.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rballe.Text = "alle TSK-Beihifen";
			this.rballe.Location = new System.Drawing.Point(23, 71);
			this.rballe.Size = new System.Drawing.Size(138, 24);
			this.rballe.TabIndex = 3;
			// 
			// pbAnzeigen
			// 
			this.pbAnzeigen.Name = "pbAnzeigen";
			this.pbAnzeigen.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAnzeigen.Text = "&Ok";
			this.pbAnzeigen.Location = new System.Drawing.Point(539, 23);
			this.pbAnzeigen.Size = new System.Drawing.Size(90, 56);
			this.pbAnzeigen.Image = global::Moveta.Intern.Properties.Resources.ok;
			this.pbAnzeigen.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAnzeigen.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAnzeigen_WindowActions);
			this.pbAnzeigen.TabIndex = 4;
			// 
			// grp2
			// 
			this.grp2.Name = "grp2";
			this.grp2.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.grp2.Text = "Tabelle Drucken";
			this.grp2.Location = new System.Drawing.Point(689, 7);
			this.grp2.Size = new System.Drawing.Size(396, 88);
			this.grp2.TabIndex = 5;
			// 
			// pbDrucken
			// 
			this.pbDrucken.Name = "pbDrucken";
			this.pbDrucken.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbDrucken.Text = "&drucken";
			this.pbDrucken.Location = new System.Drawing.Point(983, 23);
			this.pbDrucken.Size = new System.Drawing.Size(90, 56);
			this.pbDrucken.Image = global::Moveta.Intern.Properties.Resources.printer;
			this.pbDrucken.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbDrucken.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbDrucken_WindowActions);
			this.pbDrucken.TabIndex = 6;
			// 
			// pbErinnerung
			// 
			this.pbErinnerung.Name = "pbErinnerung";
			this.pbErinnerung.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbErinnerung.Text = "Erinnerung drucken";
			this.pbErinnerung.Location = new System.Drawing.Point(1113, 23);
			this.pbErinnerung.Size = new System.Drawing.Size(146, 56);
			this.pbErinnerung.Image = global::Moveta.Intern.Properties.Resources.printer;
			this.pbErinnerung.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbErinnerung.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbErinnerung_WindowActions);
			this.pbErinnerung.TabIndex = 7;
			// 
			// lbPrinters
			// 
			this.lbPrinters.Name = "lbPrinters";
			this.lbPrinters.HorizontalScrollbar = false;
			this.lbPrinters.BackColor = System.Drawing.Color.White;
			this.lbPrinters.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.lbPrinters.SelectionMode = System.Windows.Forms.SelectionMode.One;
			this.lbPrinters.Sorted = false;
			this.lbPrinters.Location = new System.Drawing.Point(701, 23);
			this.lbPrinters.Size = new System.Drawing.Size(270, 56);
			this.lbPrinters.TabIndex = 8;
			// 
			// tblBeihilfen
			// 
			this.tblBeihilfen.Name = "tblBeihilfen";
			this.tblBeihilfen.BackColor = System.Drawing.Color.White;
			this.tblBeihilfen.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.tblBeihilfen.Location = new System.Drawing.Point(17, 103);
			this.tblBeihilfen.Size = new System.Drawing.Size(1368, 560);
			this.tblBeihilfen.UseVisualStyles = true;
			// 
			// tblBeihilfen.colsRegArzt
			// 
			this.tblBeihilfen.colsRegArzt.Name = "colsRegArzt";
			this.tblBeihilfen.colsRegArzt.Title = "Reg.Nr.\r\nArzt";
			this.tblBeihilfen.colsRegArzt.Width = 84;
			this.tblBeihilfen.colsRegArzt.Enabled = false;
			this.tblBeihilfen.colsRegArzt.Position = 1;
			// 
			// tblBeihilfen.colnArztNr
			// 
			this.tblBeihilfen.colnArztNr.Name = "colnArztNr";
			this.tblBeihilfen.colnArztNr.Title = "Arzt-Nr.";
			this.tblBeihilfen.colnArztNr.Width = 53;
			this.tblBeihilfen.colnArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.tblBeihilfen.colnArztNr.Enabled = false;
			this.tblBeihilfen.colnArztNr.Format = "0";
			this.tblBeihilfen.colnArztNr.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblBeihilfen.colnArztNr.Position = 2;
			// 
			// tblBeihilfen.colsNameArzt
			// 
			this.tblBeihilfen.colsNameArzt.Name = "colsNameArzt";
			this.tblBeihilfen.colsNameArzt.Title = "Name\r\nArzt";
			this.tblBeihilfen.colsNameArzt.Width = 132;
			this.tblBeihilfen.colsNameArzt.Enabled = false;
			this.tblBeihilfen.colsNameArzt.Position = 3;
			// 
			// tblBeihilfen.colsRegHalter
			// 
			this.tblBeihilfen.colsRegHalter.Name = "colsRegHalter";
			this.tblBeihilfen.colsRegHalter.Title = "Reg.Nr.\r\nHalter";
			this.tblBeihilfen.colsRegHalter.Width = 135;
			this.tblBeihilfen.colsRegHalter.Enabled = false;
			this.tblBeihilfen.colsRegHalter.Position = 4;
			// 
			// tblBeihilfen.colsNameHalter
			// 
			this.tblBeihilfen.colsNameHalter.Name = "colsNameHalter";
			this.tblBeihilfen.colsNameHalter.Title = "Name\r\nHalter";
			this.tblBeihilfen.colsNameHalter.Width = 133;
			this.tblBeihilfen.colsNameHalter.Enabled = false;
			this.tblBeihilfen.colsNameHalter.Position = 5;
			// 
			// tblBeihilfen.coldtDatum
			// 
			this.tblBeihilfen.coldtDatum.Name = "coldtDatum";
			this.tblBeihilfen.coldtDatum.Title = "Datum";
			this.tblBeihilfen.coldtDatum.DataType = PPJ.Runtime.Windows.DataType.DateTime;
			this.tblBeihilfen.coldtDatum.Enabled = false;
			this.tblBeihilfen.coldtDatum.Format = "dd.MM.yyyy";
			this.tblBeihilfen.coldtDatum.Position = 6;
			// 
			// tblBeihilfen.colnAnzahl
			// 
			this.tblBeihilfen.colnAnzahl.Name = "colnAnzahl";
			this.tblBeihilfen.colnAnzahl.Title = "Anzahl";
			this.tblBeihilfen.colnAnzahl.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.tblBeihilfen.colnAnzahl.Enabled = false;
			this.tblBeihilfen.colnAnzahl.Format = "0";
			this.tblBeihilfen.colnAnzahl.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblBeihilfen.colnAnzahl.Position = 7;
			// 
			// tblBeihilfen.colnBetrag
			// 
			this.tblBeihilfen.colnBetrag.Name = "colnBetrag";
			this.tblBeihilfen.colnBetrag.Title = "Betrag";
			this.tblBeihilfen.colnBetrag.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.tblBeihilfen.colnBetrag.Enabled = false;
			this.tblBeihilfen.colnBetrag.Format = "#,##0.00";
			this.tblBeihilfen.colnBetrag.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblBeihilfen.colnBetrag.Position = 8;
			// 
			// tblBeihilfen.coldtEinleseDatum
			// 
			this.tblBeihilfen.coldtEinleseDatum.Name = "coldtEinleseDatum";
			this.tblBeihilfen.coldtEinleseDatum.Title = "Einlese\r\nDatum";
			this.tblBeihilfen.coldtEinleseDatum.Width = 92;
			this.tblBeihilfen.coldtEinleseDatum.DataType = PPJ.Runtime.Windows.DataType.DateTime;
			this.tblBeihilfen.coldtEinleseDatum.Enabled = false;
			this.tblBeihilfen.coldtEinleseDatum.Format = "dd.MM.yyyy";
			this.tblBeihilfen.coldtEinleseDatum.Position = 9;
			// 
			// tblBeihilfen.coldtErlDatum
			// 
			this.tblBeihilfen.coldtErlDatum.Name = "coldtErlDatum";
			this.tblBeihilfen.coldtErlDatum.Title = "erledigt am";
			this.tblBeihilfen.coldtErlDatum.Width = 90;
			this.tblBeihilfen.coldtErlDatum.DataType = PPJ.Runtime.Windows.DataType.DateTime;
			this.tblBeihilfen.coldtErlDatum.Enabled = false;
			this.tblBeihilfen.coldtErlDatum.Format = "dd.MM.yyyy";
			this.tblBeihilfen.coldtErlDatum.Position = 10;
			// 
			// tblBeihilfen.colsGUID
			// 
			this.tblBeihilfen.colsGUID.Name = "colsGUID";
			this.tblBeihilfen.colsGUID.Title = "GUID";
			this.tblBeihilfen.colsGUID.Width = 93;
			this.tblBeihilfen.colsGUID.Enabled = false;
			this.tblBeihilfen.colsGUID.Position = 11;
			// 
			// tblBeihilfen.colsStatus
			// 
			this.tblBeihilfen.colsStatus.Name = "colsStatus";
			this.tblBeihilfen.colsStatus.Title = "Status";
			this.tblBeihilfen.colsStatus.Width = 183;
			this.tblBeihilfen.colsStatus.Enabled = false;
			this.tblBeihilfen.colsStatus.Position = 12;
			// 
			// tblBeihilfen.colnRechNr
			// 
			this.tblBeihilfen.colnRechNr.Name = "colnRechNr";
			this.tblBeihilfen.colnRechNr.Title = "Rech-Nr.";
			this.tblBeihilfen.colnRechNr.Width = 59;
			this.tblBeihilfen.colnRechNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.tblBeihilfen.colnRechNr.Enabled = false;
			this.tblBeihilfen.colnRechNr.Format = "0";
			this.tblBeihilfen.colnRechNr.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.tblBeihilfen.colnRechNr.Position = 13;
			this.tblBeihilfen.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.tblBeihilfen_WindowActions);
			this.tblBeihilfen.TabIndex = 9;
			// 
			// grpSort
			// 
			this.grpSort.Name = "grpSort";
			this.grpSort.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.grpSort.Text = "Sortierung";
			this.grpSort.Location = new System.Drawing.Point(221, 7);
			this.grpSort.Size = new System.Drawing.Size(138, 88);
			this.grpSort.TabIndex = 10;
			// 
			// rbSortEinleseDatum
			// 
			this.rbSortEinleseDatum.Name = "rbSortEinleseDatum";
			this.rbSortEinleseDatum.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rbSortEinleseDatum.Text = "Einlesedatum";
			this.rbSortEinleseDatum.Location = new System.Drawing.Point(233, 31);
			this.rbSortEinleseDatum.Size = new System.Drawing.Size(114, 24);
			this.rbSortEinleseDatum.TabIndex = 11;
			// 
			// rbSortRegArzt
			// 
			this.rbSortRegArzt.Name = "rbSortRegArzt";
			this.rbSortRegArzt.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.rbSortRegArzt.Text = "ArztNr";
			this.rbSortRegArzt.Location = new System.Drawing.Point(233, 55);
			this.rbSortRegArzt.Size = new System.Drawing.Size(108, 24);
			this.rbSortRegArzt.TabIndex = 12;
			// 
			// bkgd1
			// 
			this.bkgd1.Name = "bkgd1";
			this.bkgd1.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd1.Text = "Arzt-Nr.";
			this.bkgd1.Location = new System.Drawing.Point(371, 17);
			this.bkgd1.Size = new System.Drawing.Size(66, 16);
			this.bkgd1.TabIndex = 13;
			// 
			// bkgd2
			// 
			this.bkgd2.Name = "bkgd2";
			this.bkgd2.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd2.Text = "Haltername";
			this.bkgd2.Location = new System.Drawing.Point(371, 57);
			this.bkgd2.Size = new System.Drawing.Size(66, 16);
			this.bkgd2.TabIndex = 14;
			// 
			// dfArztNr
			// 
			this.dfArztNr.Name = "dfArztNr";
			this.dfArztNr.BackColor = System.Drawing.Color.White;
			this.dfArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfArztNr.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfArztNr.Format = "#0";
			this.dfArztNr.Location = new System.Drawing.Point(443, 15);
			this.dfArztNr.Size = new System.Drawing.Size(72, 24);
			this.dfArztNr.TabIndex = 15;
			// 
			// dfHalterName
			// 
			this.dfHalterName.Name = "dfHalterName";
			this.dfHalterName.BackColor = System.Drawing.Color.White;
			this.dfHalterName.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfHalterName.Location = new System.Drawing.Point(443, 55);
			this.dfHalterName.Size = new System.Drawing.Size(72, 24);
			this.dfHalterName.TabIndex = 16;
			// 
			// bkgd3
			// 
			this.bkgd3.Name = "bkgd3";
			this.bkgd3.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd3.Text = "älter als";
			this.bkgd3.Location = new System.Drawing.Point(1265, 33);
			this.bkgd3.Size = new System.Drawing.Size(54, 16);
			this.bkgd3.TabIndex = 17;
			// 
			// dfMonate
			// 
			this.dfMonate.Name = "dfMonate";
			this.dfMonate.BackColor = System.Drawing.Color.White;
			this.dfMonate.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.dfMonate.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.dfMonate.Format = "#0";
			this.dfMonate.Location = new System.Drawing.Point(1265, 55);
			this.dfMonate.Size = new System.Drawing.Size(48, 24);
			this.dfMonate.TabIndex = 18;
			// 
			// bkgd4
			// 
			this.bkgd4.Name = "bkgd4";
			this.bkgd4.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.bkgd4.Text = "Monate";
			this.bkgd4.Location = new System.Drawing.Point(1319, 57);
			this.bkgd4.Size = new System.Drawing.Size(48, 16);
			this.bkgd4.TabIndex = 19;
			// 
			// frmTSKBeihilfen
			// 
			this.Controls.Add(this.ClientArea);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "frmTSKBeihilfen";
			this.ClientSize = new System.Drawing.Size(1424, 720);
			this.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.ForeColor = System.Drawing.SystemColors.WindowText;
			this.Text = "TSK-Beihilfen";
			this.Location = new System.Drawing.Point(46, 52);
			this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
			this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.frmTSKBeihilfen_WindowActions);
			this.ToolBar.ResumeLayout(false);
			this.ClientArea.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.frmTSKBeihilfen == this) 
			{
				App.frmTSKBeihilfen = null;
			}
			base.Dispose(disposing);
		}
		#endregion
		
		#region tblBeihilfen
		
		public partial class tblBeihilfenTableWindow
		{
			#region Window Controls
			public SalTableColumn colsRegArzt;
			public SalTableColumn colnArztNr;
			public SalTableColumn colsNameArzt;
			public SalTableColumn colsRegHalter;
			public SalTableColumn colsNameHalter;
			public SalTableColumn coldtDatum;
			public SalTableColumn colnAnzahl;
			public SalTableColumn colnBetrag;
			public SalTableColumn coldtEinleseDatum;
			public SalTableColumn coldtErlDatum;
			public SalTableColumn colsGUID;
			public SalTableColumn colsStatus;
			public SalTableColumn colnRechNr;
			#endregion
			
			#region Windows Form Designer generated code
			
			/// <summary>
			/// Required method for Designer support - do not modify
			/// the contents of this method with the code editor.
			/// </summary>
			private void InitializeComponent()
			{
				this.colsRegArzt = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnArztNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsNameArzt = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsRegHalter = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsNameHalter = new PPJ.Runtime.Windows.SalTableColumn();
				this.coldtDatum = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnAnzahl = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnBetrag = new PPJ.Runtime.Windows.SalTableColumn();
				this.coldtEinleseDatum = new PPJ.Runtime.Windows.SalTableColumn();
				this.coldtErlDatum = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsGUID = new PPJ.Runtime.Windows.SalTableColumn();
				this.colsStatus = new PPJ.Runtime.Windows.SalTableColumn();
				this.colnRechNr = new PPJ.Runtime.Windows.SalTableColumn();
				this.SuspendLayout();
				// 
				// colsRegArzt
				// 
				this.colsRegArzt.Name = "colsRegArzt";
				// 
				// colnArztNr
				// 
				this.colnArztNr.Name = "colnArztNr";
				// 
				// colsNameArzt
				// 
				this.colsNameArzt.Name = "colsNameArzt";
				// 
				// colsRegHalter
				// 
				this.colsRegHalter.Name = "colsRegHalter";
				// 
				// colsNameHalter
				// 
				this.colsNameHalter.Name = "colsNameHalter";
				// 
				// coldtDatum
				// 
				this.coldtDatum.Name = "coldtDatum";
				// 
				// colnAnzahl
				// 
				this.colnAnzahl.Name = "colnAnzahl";
				// 
				// colnBetrag
				// 
				this.colnBetrag.Name = "colnBetrag";
				// 
				// coldtEinleseDatum
				// 
				this.coldtEinleseDatum.Name = "coldtEinleseDatum";
				// 
				// coldtErlDatum
				// 
				this.coldtErlDatum.Name = "coldtErlDatum";
				// 
				// colsGUID
				// 
				this.colsGUID.Name = "colsGUID";
				// 
				// colsStatus
				// 
				this.colsStatus.Name = "colsStatus";
				// 
				// colnRechNr
				// 
				this.colnRechNr.Name = "colnRechNr";
				// 
				// tblBeihilfen
				// 
				this.Controls.Add(this.colsRegArzt);
				this.Controls.Add(this.colnArztNr);
				this.Controls.Add(this.colsNameArzt);
				this.Controls.Add(this.colsRegHalter);
				this.Controls.Add(this.colsNameHalter);
				this.Controls.Add(this.coldtDatum);
				this.Controls.Add(this.colnAnzahl);
				this.Controls.Add(this.colnBetrag);
				this.Controls.Add(this.coldtEinleseDatum);
				this.Controls.Add(this.coldtErlDatum);
				this.Controls.Add(this.colsGUID);
				this.Controls.Add(this.colsStatus);
				this.Controls.Add(this.colnRechNr);
				this.Name = "tblBeihilfen";
				this.ResumeLayout(false);
			}
			#endregion
		}
		#endregion
	}
}
