// <ppj name="Moveta.Intern" date="1/17/2024 7:59:41 AM" id="F4EC85BAD2BF79AC25C9F8643540E90F9BE1DAF0"/>
// ======================================================================================================
// This code was generated by the Ice Porter(tm) Tool version 4.8.15.0
// Ice Porter is part of The Porting Project (PPJ) by Ice Tea Group, LLC.
// The generated code is not guaranteed to be accurate and to compile without
// manual modifications.
// 
// ICE TEA GROUP LLC SHALL IN NO EVENT BE LIABLE FOR ANY DAMAGES WHATSOEVER
// (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS
// INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER LOSS OF ANY KIND)
// ARISING OUT OF THE USE OR INABILITY TO USE THE GENERATED CODE, WHETHER
// DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL OR OTHERWISE, REGARDLESS
// OF THE FORM OF ACTION, EVEN IF ICE TEA GROUP LLC HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.
// =====================================================================================================
using System;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Collections;
using System.Windows.Forms;
using System.ComponentModel;
using MT;
using PPJ.Runtime;
using PPJ.Runtime.Com;
using PPJ.Runtime.Sql;
using PPJ.Runtime.Vis;
using PPJ.Runtime.Windows;
using PPJ.Runtime.Windows.QO;
using PPJ.Runtime.XSal;

namespace Moveta.Intern
{
	
	public partial class tblArzt
	{
		
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		#region Window Accessories
		
		/// <summary>
		/// Toolbar control.
		/// </summary>
		protected SalFormToolBar ToolBar;
		
		/// <summary>
		/// StatusBar control.
		/// </summary>
		protected SalFormStatusBar StatusBar;
		#endregion
		
		
		#region Window Controls
		public SalPushbutton pbAbbruch;
		public SalTableColumn colnArztNr;
		public SalTableColumn colstrName;
		public SalTableColumn colstrName2;
		public SalTableColumn colstrStrasse;
		public SalTableColumn colstrOrt;
		public SalTableColumn coldtBeitritt;
		#endregion
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.ToolBar = new PPJ.Runtime.Windows.SalFormToolBar();
			this.StatusBar = new PPJ.Runtime.Windows.SalFormStatusBar();
			this.pbAbbruch = new PPJ.Runtime.Windows.SalPushbutton();
			this.colnArztNr = new PPJ.Runtime.Windows.SalTableColumn();
			this.colstrName = new PPJ.Runtime.Windows.SalTableColumn();
			this.colstrName2 = new PPJ.Runtime.Windows.SalTableColumn();
			this.colstrStrasse = new PPJ.Runtime.Windows.SalTableColumn();
			this.colstrOrt = new PPJ.Runtime.Windows.SalTableColumn();
			this.coldtBeitritt = new PPJ.Runtime.Windows.SalTableColumn();
			this.ToolBar.SuspendLayout();
			this.SuspendLayout();
			// 
			// ToolBar
			// 
			this.ToolBar.Name = "ToolBar";
			this.ToolBar.Font = new Font("Tahoma", 8f, System.Drawing.FontStyle.Regular);
			this.ToolBar.TabStop = true;
			this.ToolBar.Visible = false;
			this.ToolBar.Controls.Add(this.pbAbbruch);
			// 
			// StatusBar
			// 
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Visible = true;
			// 
			// pbAbbruch
			// 
			this.pbAbbruch.Name = "pbAbbruch";
			this.pbAbbruch.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Bold);
			this.pbAbbruch.AcceleratorKey = Keys.Escape;
			this.pbAbbruch.Text = "Abbruch";
			this.pbAbbruch.Location = new System.Drawing.Point(-25, -42);
			this.pbAbbruch.Size = new System.Drawing.Size(25, 42);
			this.pbAbbruch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.pbAbbruch.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.pbAbbruch_WindowActions);
			this.pbAbbruch.TabIndex = 0;
			// 
			// colnArztNr
			// 
			this.colnArztNr.Name = "colnArztNr";
			this.colnArztNr.Title = "Arzt";
			this.colnArztNr.Width = 29;
			this.colnArztNr.DataType = PPJ.Runtime.Windows.DataType.Number;
			this.colnArztNr.Enabled = false;
			this.colnArztNr.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
			this.colnArztNr.TabIndex = 0;
			// 
			// colstrName
			// 
			this.colstrName.Name = "colstrName";
			this.colstrName.Title = "Name";
			this.colstrName.Width = 125;
			this.colstrName.Enabled = false;
			this.colstrName.TabIndex = 1;
			// 
			// colstrName2
			// 
			this.colstrName2.Name = "colstrName2";
			this.colstrName2.Title = "Name 2";
			this.colstrName2.Width = 142;
			this.colstrName2.Enabled = false;
			this.colstrName2.TabIndex = 2;
			// 
			// colstrStrasse
			// 
			this.colstrStrasse.Name = "colstrStrasse";
			this.colstrStrasse.Title = "Straße";
			this.colstrStrasse.Width = 140;
			this.colstrStrasse.Enabled = false;
			this.colstrStrasse.TabIndex = 3;
			// 
			// colstrOrt
			// 
			this.colstrOrt.Name = "colstrOrt";
			this.colstrOrt.Title = "Ort";
			this.colstrOrt.Width = 104;
			this.colstrOrt.Enabled = false;
			this.colstrOrt.TabIndex = 4;
			// 
			// coldtBeitritt
			// 
			this.coldtBeitritt.Name = "coldtBeitritt";
			this.coldtBeitritt.Title = "Beitritt";
			this.coldtBeitritt.Width = 104;
			this.coldtBeitritt.DataType = PPJ.Runtime.Windows.DataType.DateTime;
			this.coldtBeitritt.Enabled = false;
			this.coldtBeitritt.Format = "dd.MM.yyyy";
			this.coldtBeitritt.TabIndex = 5;
			// 
			// tblArzt
			// 
			this.Controls.Add(this.colnArztNr);
			this.Controls.Add(this.colstrName);
			this.Controls.Add(this.colstrName2);
			this.Controls.Add(this.colstrStrasse);
			this.Controls.Add(this.colstrOrt);
			this.Controls.Add(this.coldtBeitritt);
			this.Controls.Add(this.ToolBar);
			this.Controls.Add(this.StatusBar);
			this.Name = "tblArzt";
			this.ClientSize = new System.Drawing.Size(1136, 600);
			this.Font = new Font("Tahoma", 9f, System.Drawing.FontStyle.Regular);
			this.Text = "Ärzte";
			this.Location = new System.Drawing.Point(201, 96);
			this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
			this.UseVisualStyles = true;
			this.WindowActions += new PPJ.Runtime.Windows.WindowActionsEventHandler(this.tblArzt_WindowActions);
			this.ToolBar.ResumeLayout(false);
			this.ResumeLayout(false);
		}
		#endregion
		
		#region System Methods/Properties
		
		/// <summary>
		/// Release global reference.
		/// </summary>
		/// <param name="disposing"></param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null) 
			{
				components.Dispose();
			}
			if (disposing && App.tblArzt == this) 
			{
				App.tblArzt = null;
			}
			base.Dispose(disposing);
		}
		#endregion
	}
}
